nodeLinker: node-modules
packageExtensions:
  "@inversifyjs/core@*":
    dependencies:
      "reflect-metadata": "^0.2.2"
  "antd-style@*":
    dependencies:
      "react-dom": "^18.3.1"
  "serverless-tencent@*":
    dependencies:
      "inquirer": "^8.2.6"
  "swagger-parser@*":
    dependencies:
      "openapi-types": "^12.1.0"
  "ts-node-dev@*":
    dependencies:
      "@types/node": "^22.0.0"
