// .languageConfig.ts
// User language config: extracted from frontend-common/language.ts.
import { MEDIA_PLATFORM_MAP } from '@ecuc/shared/constants/media.constants';
import {
    TICKET_TYPE_NAME_MAP,
    INITIATOR_LABELS,
    TARGET_LABELS,
    TICKET_STATUS_NAME_MAP,
} from '@ecuc/shared/constants/ticket.constants';
type LanguageConfig = {
    [key: string]: string | string[] | LanguageConfig;
};

export const languageConfig: Readonly<LanguageConfig> = {
    globalNotice:
        '欢迎回来！EaseCation 用户中心2.0（原工单系统）现已正式上线！我们由衷希望您能够为我们提出宝贵的意见与建议，请通过提交"其他服务"工单向我们反馈，对于优质反馈，我们会发放一定的小礼品哦～ 由于新系统可能存在较多BUG，给您带来不便敬请谅解！',
    required: '必填',
    more: '更多',
    loading: '加载中...',
    vip1: 'VIP 1',
    vip2: 'VIP 2',
    ok: '确认',
    vip3: 'VIP 3',
    vip4: 'VIP 4',
    admin1: '实习管理员',
    admin2: '管理员',
    admin3: '高级管理员',
    admin4: '超级管理员',
    admin5: '服主',
    frozen: '已冻结',
    normalPlayer: '普通用户',
    media1: '土豆创作者',
    media2: '土豆创作者',
    media3: '卓越创作者',
    inProgress: '处理中...',
    success: '成功',
    error: {
        general: '出错啦',
        backendCrashed: '服务器节点玩累啦，稍微让它喝口水休息一下吧～',
        activelyFixing: '可能是服务器维护或后端直接炸掉导致的。请稍后再试，或者刷新页面重新加载',
    },
    retry: '重试',
    cancel: '取消',
    save: '保存',
    confirm: '确认',
    noPermission: '你没有权限访问此页面哦',
    themeSettings: '切换主题',
    files: {
        btn: '上传附件',
        uploading: '正在上传 {name}...',
        uploadingText: '上传中...',
        uploadingProgress: '正在上传 {name}... {percent}%',
        mustImgOrVideo: '文件必须是图片或视频',
        moreThan100MB: '文件大小必须小于100MB，推荐剪切视频分次发送。',
        success: '上传成功',
        failed: '上传失败',
        limitExceeded: '已达到最大上传数量(10个)',
        noHashSymbol: '文件名不能包含 # 符号',
        unsupportedFormat:
            '仅支持上传视频(mp4、mov、webm)、图片(jpg、jpeg、png、gif、bmp、webp、svg)和PDF文件',
    },
    footer: {
        copyright: 'EaseCation © {year} 宁波易什网络科技有限公司',
        icp: '浙ICP备2022033471号-1',
    },
    pageTitle: {
        '/': '主页',
        '/document': '文档中心',
        '/media': '创作者中心',
        '/media/shop': '创作者商城',
        '/media-guidelines': '创作者守则',
        '/shop-guidelines': '创作者商城',
        '/player-guidelines': '玩家守则',
        '/general-guidelines': '总则',
        '/lotteries': '抽奖箱概率表',
        '/login': '登录',
        '/account': '我的游戏账号',
        '/account/:ecid': '账号详情',
        '/account/:ecid/manage': '账号管理',
        '/scoretop': '排行榜',
        '/ticket': '工单',
        '/ticket/new': '创建工单',
        '/resources': '更多资源',
        '/resources/wiki': 'Wiki绑定',
        '/sgmatch': '饥饿游戏 吃饱杯',
        '/feedback': '反馈中心',
        '/feedback/subscriptions': '我的订阅',
        '/feedback/settings': '反馈设置',
        '/tlgift': '原石商城',
        userCenter: '用户中心',
        userCenterSuffix: '{pageTitle} - 用户中心',
    },
    tlgift: {
        title: '原石商城',
        tabConsume: '消费原石',
        tabLogs: '我的记录',
        noProducts: '暂无商品',
        cart: '购物车',
        cartSummary: '共 {kind} 种、{qty} 件',
        cartEstimate: '预估 {primogems} 原石',
        settle: '结算',
        exportConfig: '导出配置',
        importConfig: '导入配置',
        clear: '清空',
        clearSuccess: '已清空',
        cartEmpty: '购物车为空',
        targetEcid: '目标玩家 ECID',
        targetEcidPlaceholder: '填写 ECID 后可校验每项限购并结算',
        perItemPrice: '{price} 原石/件 × {qty} = {sub} 原石',
        overLimitOrSoldOut: '（超出限购或已售罄）',
        confirmSettle: '确认结算',
        confirmSettleEcid: '使用 ECID：',
        confirmSettleSummary: '共 {kind} 种商品、{qty} 件，合计 {primogems} 原石。',
        confirmSettleHint: '将按顺序逐笔扣款，请确保原石余额充足。',
        importModalTitle: '导入购物车配置',
        importModalPlaceholder: '粘贴之前导出的购物车配置（JSON）',
        importBtn: '导入',
        copySuccess: '已复制到剪贴板',
        copyFailed: '复制失败',
        exportEmpty: '购物车为空，无需导出',
        importInvalidFormat: '无法识别的格式',
        importInvalidJson: '粘贴内容不是有效的 JSON',
        importNoValidItems: '没有有效的商品项',
        importSuccess: '已导入 {count} 项',
        settleEcidRequired: '请先填写目标玩家 ECID',
        settleFailed: '结算失败',
        settleSuccess: '结算完成',
        requestFailed: '请求失败',
        logsTitle: '消费记录',
        myLogs: '我的记录',
        selectTarget: '选择查看',
        tableTime: '时间',
        tableType: '类型',
        tableAmount: '原石',
        tableEcid: '目标 ECID',
        tableProduct: '兑换内容',
        logTypeConsume: '消费',
        logTypeAdjust: '调整',
        loginRequiredForLogs: '请先登录后查看记录',
        primogemsUnit: '原石',
        primogemsPerItem: '原石/件',
        balanceTitle: '原石余额',
        balanceSubtitle: '消费原石可为指定 ECID 发放商品',
        soldOut: '已售罄',
        usedUp: '已用完',
        addToCart: '加入购物车',
        soldCount: '已兑 {count}',
        consumeTitle: '消费原石',
        limitInfo: '限购信息',
        totalLimit: '总限购',
        totalRemaining: '剩余 {remaining} / {total}',
        remainingShort: '剩余 {remaining}',
        userLimit: '账号限购',
        userRemaining: '您的账号剩余 {remaining} / {total}',
        personLimit: '该 ECID 限购',
        personRemainingQuery: '填写 ECID 后自动查询',
        personEcidRequired: '请先填写 ECID',
        querying: '查询中…',
        personRemaining: '剩余 {remaining} / {total}',
        fillInfo: '填写信息',
        ecidLabel: '目标玩家 ECID',
        ecidRequired: '请填写 ECID',
        ecidPlaceholder: '请输入 ECID',
        quantity: '数量',
        totalSoldOut: '总限购已售罄',
        userSoldOut: '账号限购已用完',
        personSoldOut: '该 ECID 限购已用完',
        insufficientBalance: '原石不足',
        submitting: '提交中…',
        confirmConsume: '确认消费',
        addToCartWithQty: '加入购物车',
        addedToCart: '已加入购物车',
        paymentInfo: '支付信息',
        balance: '原石余额',
        costThis: '本次消耗',
        consumeSuccess: '消费成功',
        consumeFailed: '失败',
        searchPlaceholder: '搜索商品名称',
        allProducts: '全部商品',
        noMatchFound: '没有找到匹配的商品',
        categoryParkour: 'parkour',
    },
    notFound: {
        title: 'EC娘走丢啦',
        goHome: '帮我回家',
        currentPath: '当前路径：{path}',
    },
    dashboard: {
        title: '用户中心',
        intro: '欢迎使用EaseCation用户中心！您可以在这里绑定和查看游戏账号数据并发起工单。我们的团队会尽全力为您提供最优质的服务。',
        logout: '退出登录',
        ec: '游戏账号',
        media: '创作者中心',
        ticket: '我的工单',
        scoretop: '排行榜',
        admin: '工单系统',
        sgmatch: '饥饿游戏《吃饱杯》🎉',
        sgmatch_desc: '比赛火爆进行中～ 点此进入查看实时比分！',
        gameAccount: '我的游戏账号',
        gameAccountDesc: '绑定并管理游戏账号',
        mediaCenter: '创作者中心',
        mediaCenterDesc: '媒体商城已向全体玩家开放！',
        playerGuidelines: '玩家守则',
        playerGuidelinesDesc: '做遵纪守法的小土豆',
        leaderboard: '排行榜',
        leaderboardDesc: '查看最新排行与战绩',
        ticketSystem: '工单系统',
        ticketSystemDesc: '举报、申诉、反馈',
        adminPanel: '管理面板',
        adminPanelDesc: '自研给我自信！',
        logoutDesc: '退出当前账号',
        AnnouncementCard: '公告',
        AnnouncementCardDesc: '查看以往公告',
        documentCenter: '文档中心',
        documentCenterDesc: '查看各类守则与文档',
        moreResources: '更多资源',
        moreResourcesDesc: '查看更多常用站点与工具',
        feedbackCenter: '反馈中心',
        feedbackCenterDesc: '查看和订阅官方反馈',
    },
    ecList: {
        title: '我的游戏账号',
        intro: '您可以进入游戏后在右前方 "EC玩家大使" NPC处选择 "绑定EC工单系统" 并再次点击 "绑定入口" 来获取您的6位数字专属绑定验证码并绑定游戏账号！',
        frozen: '已冻结',
        bindBtn: '点我绑定游戏账号',
        bindTitle: '绑定游戏账号',
        bindColumn: '绑定验证码',
        bindSixDigits: '验证码应当为6位数字',
        bindSubmit: '绑定',
        bindIntro: '绑定验证码获取方式：大厅右前方 EC玩家大使NPC —— 绑定EC工单系统 —— 绑定入口',
    },
    ecDetail: {
        frozen1: '您的账号已被管理员冻结',
        frozen2: '冻结后无法发起工单，请提交 解封申请 工单',
        token: '点券余额',
        diamond: '钻石余额',
        coin: 'EC币余额',
        playerPrivilege: '玩家特权',
        mediaPrivilege: '媒体特权',
        specialPrivilege: '管理权限',
        latestOnlineTime: '最后上线时间',
        nextLevelExp: '距离下一级所需经验',
        unbindBtn: '解绑',
        unbindTitle: '确认解绑该账号吗？',
        unbindIntro: '解绑后需要重新绑定，是否继续',
        unbindConfirm: '确认解绑',
        unbindCancel: '我再想想',
        giftBtn: '给好友赠送VIP',
        giftNeedVip2: '你至少需要拥有VIP2，才可以赠送其他玩家VIP哦～',
        giftNeedExpire: '你的VIP有效期必须大于7天，才可以赠送其他玩家VIP哦～',
        giftLevel: 'VIP等级',
        giftEcid: '被赠送人',
        giftEcidIntro: '请输入对方的昵称或ECID，随后在下方选择匹配的玩家',
        giftIntro1:
            '赠送前请确认您已正确匹配对方ECID，赠送成功后对方需要在 10分钟内 进入服务器领取，否则无法领取且不退还额度。请您仔细核对赠送信息，管理员和客服无权给您退还额度。',
        giftIntro2: '赠送VIP需要赠送方等级大于50，没有被冻结的ECID，无生效处罚记录。',
        giftLeft: ' (可赠送给 {left} 位好友)',
        giftSubmit: '赠送',
        giftSuccess: '赠送成功，对方需在10分钟内进入服务器领取',
        delRespackCache: '清空云材质缓存',
        delRespackCacheConfirmTitle: '确认清空云材质缓存？',
        delRespackCacheConfirm1:
            '当你装备的多个云材质因冲突导致无法进入游戏时，可以使用此功能暂时卸载云材质，以便顺利进入游戏。',
        delRespackCacheConfirm2:
            '清空缓存后，云材质仅在下次进入游戏时不加载，实际上并未完全卸载。你需要进入游戏后立即手动卸载云材质，才能彻底解决无法进入的问题。',
        delRespackCacheSuccessTitle: '云材质缓存已成功清空',
        delRespackCacheSuccess: '请立即进入游戏并卸载云材质，否则云材质仍会继续加载。',
        giftEcidChooseRequired: '请选择一个匹配的玩家',
        giftEcidNotFound: '未找到匹配的玩家',
        bestMatchPlaceholder: '请输入被赠送者昵称或ECID',
        manageAccount: '管理账号',
        email: '邮箱',
        emailSettings: '邮箱设置',
        emailAddress: '邮箱地址',
        emailPlaceholder: '请输入邮箱地址',
        saveChanges: '保存修改',
        securityEmailStatus: '密保邮箱状态',
        securityEmail: '密保邮箱',
        notActivated: '未激活',
        clearSecurity: '清除密保',
        setSecurity: '设为密保',
        clearSecurityConfirm: '清除密保邮箱',
        setSecurityConfirm: '设置为密保邮箱',
        clearSecurityDesc: '清除后，该邮箱将不再具有密保功能，无法用于重置账号密码。',
        setSecurityDesc: '设置后，该邮箱可用于重置账号密码。请确保邮箱地址正确且可正常接收邮件。',
        understandAndAgree: '我了解并同意以上说明',
        confirmClear: '确认清除',
        confirmSet: '确认设置',
        needClearSecurityFirst: '需要先清除密保邮箱才能修改邮箱地址',
        emailUpdateSuccess: '邮箱更新成功',
        securitySetSuccess: '已设置为密保邮箱',
        securityClearSuccess: '已清除密保邮箱',
        returnToAccount: '返回账号详情',
        pleaseAgreeFirst: '请先勾选"了解并同意"',
        emailWillBeUsedForReset:
            '该邮箱 {email} 将可用于重置账号密码，并将获得最高账号所有权。请确保邮箱属于您本人且可正常接收邮件。 若未收到请查看垃圾邮件与广告邮件。',
        emailWillNoLongerHaveSecurity:
            '该邮箱 {email} 将不再具有密保功能，无法用于重置账号密码。 若未收到请查看垃圾邮件与广告邮件。',
        emailFormatRequired: '邮箱格式不正确，无法设置为密保邮箱。请先修改邮箱地址。',
        emailSendCooldown: '请{seconds}秒后重试',
        accountManagement: '账号管理',
        passwordManagement: '密码管理',
        changePassword: '修改密码',
        resetPassword: '重置密码',
        oldPassword: '旧密码',
        newPassword: '新密码',
        confirmNewPassword: '确认新密码',
        oldPasswordRequired: '请输入旧密码',
        newPasswordRequired: '请输入新密码',
        confirmPasswordRequired: '请确认新密码',
        passwordMinLength: '密码长度至少6位',
        passwordMismatch: '两次输入的密码不一致',
        oldPasswordPlaceholder: '请输入当前密码',
        newPasswordPlaceholder: '请输入新密码',
        confirmPasswordPlaceholder: '请再次输入新密码',
        confirmChange: '确认修改',
        confirmReset: '确认重置',
        passwordChangeSuccess: '密码修改成功，设备绑定已自动重置',
        passwordResetSuccess: '密码重置成功，设备绑定已自动重置',
        resetPasswordConfirm: '重置密码确认',
        resetPasswordDesc:
            '重置密码将清除当前密码，您将在新界面设置新密码。此操作不可撤销。 若未收到请查看垃圾邮件与广告邮件。',
        unbindWarning:
            '将会自动强制解绑所有账号。若独立ECID有处罚状态，将复制处罚到该账号被绑定的网易账号对应的网易ECID上',
        bindingInfo: '绑定信息',
        loadingBindingInfo: '正在加载绑定信息...',
        noBindingInfo: '该玩家暂无绑定信息',
        nickname: '昵称',
        boundIndependentAccount: '被绑定的独立ECID',
        boundNeteaseAccount: '绑定的网易ECID',
        actions: '操作',
        unbindAccount: '解绑账号',
        unbind: '解绑',
        confirmUnbind: '确认解绑',
        unbindConfirmDesc: '确定要解绑这个账号吗？此操作不可撤销。',
        confirmUnbindAll: '确认解绑全部账号',
        unbindAllConfirmDesc: '确定要解绑该玩家的所有绑定账号吗？此操作不可撤销。',
        unbindAll: '解绑全部账号',
        unbindAllAccounts: '解绑该玩家的所有绑定账号',
        unbindSuccess: '解绑成功',
        unbindAllSuccess: '解绑全部账号成功',
        playerBindingInfo: '玩家绑定信息',
        totalResults: '共找到 {count} 个结果',
        neteaseIdSearch: '网易ECID搜索',
        ecidSearch: '独立ECID搜索',
        passwordReset: '重置密码',
        unbindTicket: '解绑工单',
        unbindTicketBtn: '解绑工单',
        unbindTicketWarningTitle: '建议设置密保邮箱',
        unbindTicketWarningDesc:
            '您尚未设置密保邮箱，建议先设置密保邮箱以便后续进行密码重置等操作、否则造成的账号丢失等风险将由您自行承担！',
        unbindTicketConfirmTitle: '解绑工单确认',
        unbindTicketConfirmDesc:
            '解绑工单后，您将无法通过工单系统修改密码等操作，同时所有可登录您账号的设备都可进行绑定工单等操作。此操作不可撤销，请谨慎操作！',
        confirmUnbindTicket: '确认解绑',
        unbindTicketSuccess: '解绑工单成功',
        continue: '继续',
        confirm: '确认',
        cancel: '取消',
        accountMatching: {
            fieldRequired: '此字段为必填项',
            dropDownRequired: '请从下拉列表中选择用户',
            noMatch: '未找到匹配的用户',
            selectUser: '请选择用户',
        },
        accountRecovery: {
            title: '找回账号',
            description:
                '请输入您的邮箱地址和ECID，如果信息匹配，我们将发送密码重置邮件到您的邮箱，并解绑您的工单账号。 若未收到请查看垃圾邮件与广告邮件。',
            emailLabel: '邮箱地址',
            emailPlaceholder: '请输入您的邮箱地址',
            ecidLabel: 'ECID',
            ecidPlaceholder: '请输入您的ECID',
            submitButton: '发送找回邮件',
            success: '找回账号请求已提交',
            emailSent:
                '找回账号邮件已发送，请查收邮箱并点击链接重置密码，若未收到请查看垃圾邮件与广告邮件。',
            error: '操作失败，请检查邮箱和ECID是否正确',
        },
        neteaseAccountWarning:
            '目前暂不支持网易ECID更改密码，更改密码将没有任何作用，但仍支持找回账号等操作',
    },
    mediaList: {
        updateECIDIntro: '申请更换商城绑定的游戏账号',
        submitSuccess: '提交成功，预计4-7个休息日内完成审核',
        linkReq: '必须以 http:// 或 https:// 开头',
        title: '媒体账号列表',
        intro: '若您希望申请加入新媒体团队享受相关权益，请先点击下方按钮绑定账号，随后进行创作者认证。',
        underReview: '绑定审核中...',
        infoGroup: '所在媒体组',
        infoGroupExpiry: '认证有效期',
        bindBtn: '点我绑定媒体账号',
        bindSubmit: '提交审核',
        bindTitle: '绑定媒体账号',
        bindIntro:
            '在绑定时，我们建议您将【{openidLast6}】添加进您的个人简介中（只需要包含即可，无需删除原有内容，认证后可删除）以便于我们验证您对账号的所有权。',
        bindLink: '主页网址',
        bindAccountName: '账号名称',
        bindLinkIntro: '请填写您的新媒体平台个人主页网址\n（短视频平台：个人界面-分享-复制链接）',
        bindLinkIntroW: '请填写微信视频号的账号名称',
        bindPlatform: '媒体平台',
        bindAccount: '平台UID',
        bindAccountIntro:
            '如果您是B站，请直接复制UID数字链接，如123456；对于没有平台UID的，请填写唯一的识别号，例如抖音号等',
        bindAccountIntroW: '请填写微信视频号的账号名称',
        bindAccountIntroB: 'B站请直接填写UID数字，如 123456',
        bindAccountIntroShort: '短视频平台请填写平台唯一识别号（如抖音号、快手号、小红书号等）',
        bindAccountbilibili: 'B站账号',
        bindAccountIntrobilibili: '输入正确B站UID后会自动在此处匹配您的B站昵称',
        bindAccountIntroOth: '请按照 平台-UID 的格式填写 如：微博-123456',
        bindFiles: '上传证明文件',
        bindFilesIntro:
            '请上传3张包含 个人主页 带有平台UID的设置页面 在内的截图证明您对账号的所有权',
        applyTitle: '首次申请E点',
        applyIntro:
            '第一次申请需要提供您的媒体账号信息，供我们辨认。请按照下方要求填写自己的个人信息，切记是本人的！如有冒充将按照工单作假进行处理！',
        applyIntro2: '若想成为卓越创作者，请务必在其他信息里面好好介绍自己呀',
        applyMedia: '媒体账号',
        applyMediaIntro: '符合申请条件要求的账号',
        applyEcid: '游戏账号',
        updateExplain: '换绑理由',
        explainPlaceholder: '请具体阐述更换权限账号的理由',
        applyEcidIntro: '获取媒体权益的账号，该账号不允许共号。',
        monthlyEcidIntro: '您媒体账号绑定的游戏账号，如需更改请提交换绑工单。',
        rebindingEcidIntro: '请选择您要换绑到的账号。',
        applyQq: 'QQ',
        applyQqIntro: '用于我们与您取得联系',
        applyDob: '出生日期',
        applyDobIntro: '您必须年满16周岁才可以申请',
        applyDetail: '其他信息',
        applyDetailIntro:
            '请填写其他可供我们参考的信息，例如您的直播数据，代表作链接等等，也可以是您对于我们的期望，比如说主播自定义房间等',
        applySubmit: '提交审核',
        applyLevel: '申请等级',
        monthlyTitle: '申请E点',
        monthlyIntro: '提交EC相关视频申请获取E点',
        updateECIDTitle: '更换兑奖账号申请',
        currentECID: '当前ECID',
        updateECID: '申请换绑媒体权限账号。请注意，权限账号不允许共号。',
        monthlyFiles: '视频数据截图',
        monthlyFilesIntro: '请上传您的视频/账号数据截图 (最多2张)',
        monthlyLink: '本月作品链接',
        weeklyLink: '本周作品链接',
        workName: '作品名称',
        monthlyLinkIntro: '若是主播或图文博主，可上传对应的直播回放或图文链接哦',
        workNameIntro: '请输入作品名称（视频标题）',
        monthlySubmit: '提交审核',
        errorSameECID: '请不要选择与当前账号相同的账号',
        type: MEDIA_PLATFORM_MAP,
        lookGuidelines: '查看商城守则',
        lookGuidelinesDesc: '请认真阅读该文档！',
    },
    scoreTop: {
        title: '排行榜',
        all: '全部',
        empty: '这个分类下没有数据哦～',
        refresh: '刷新',
        platform: {
            pe: '手机版 (PE)',
            pc: '电脑版 (PC)',
        },
        scoreTypeBed: '毁床',
        scoreTypeDestroy: '摧毁',
        scoreTypeCrystal: '摧毁水晶',
        scoreTypeKill: '击杀',
        scoreTypeScore: '得分',
        scoreTypePoints: '分数',
        scoreTypeDeath: '死亡',
        scoreTypeTime: '时间',
        scoreTypeWin: '胜场',
        scoreTypeHeroKill: '英雄击杀',
        scoreTypeKillerKill: '杀手击杀',
        scoreTypeFinalKill: '最终击杀',
        scoreTypeHomeKill: '保卫击杀',
        scoreTypeWither: '凋灵击杀',
        scoreTypeBaige: '百格跑酷',
        scoreTypeYancong: '烟囱跑酷',
        deadlineDay: '日榜',
        deadlineWeek: '周榜',
        deadlineMonth: '月榜',
        deadlineYear: '年榜',
        deadlineForever: '总榜',
    },
    game: {
        bedwars: '水晶战争',
        grave: '墓碑',
        sg: '饥饿游戏',
        sw: '空岛战争',
        mw: '超级战墙',
        walls: '战墙',
        miniwalls: '迷你战墙',
        fb: '战桥',
        mm: '密室杀手',
        rl: '圣符传说',
        buhc: 'BuildUHC',
        buhc_nor: 'BuildUHC·普通',
        buhc_combo: 'BuildUHC·无限连击',
        buhc_sword: 'BuildUHC·单刀赴会',
        buhc_arrow: 'BuildUHC·归心似箭',
        buhc_team: 'BuildUHC·团队',
        zvs: '史蒂夫大战僵尸',
        color: '色盲派对',
        drop: '塌方跑酷',
        hunt: '躲猫猫',
        boom: '爆炸吧天空',
        mb: '速建大师',
        football: '激情斗球',
        labour: '劳动榜',
        parkour: '跑酷天堂',
        increase: '增长榜',
    },
    ticketProgressModal: {
        effort: '我们真的在尽力处理每一条工单了！',
        autoAssign:
            '系统会根据 <strong>优先等级</strong> 和 <strong>紧急程度</strong> 自动分配工单，客服并不能“挑单”处理。而工单处理时间差异，最主要的原因是：<u>工单的复杂程度不同</u>。',
        reasonIntro: '比如，以下这些情况都会导致处理时间变长：',
        reason1: '需要调查事件本身如涉及争议，需要与多部门多轮讨论、比对大量信息',
        reason2: '策划信息建言献策将在周会讨论可行性和未来发展方向，无法及时跟进',
        reason3: '涉及外挂或异常，需要等待反作弊团队与管理他的分析',
        reason4: '涉及商品/权限，需要开发团队支持，而开发一般都在排期中',
        notDelay:
            '所以，有时候你看到自己的工单“还在处理中/委托中/等待回复”，其实并不是我们在拖，而是 <strong>真的搞不定</strong>！',
        thanks: '希望你能理解，也感谢你的耐心等待。',
    },
    feedback: {
        subscribe: '订阅',
        subscribed: '订阅成功',
        unsubscribed: '取消订阅',
        subscriptionUpdateFailed: '更新订阅状态失败',
        subscriptionUpdateFailedWithColon: '更新订阅状态失败:',
        tidMissing: 'TID参数缺失',
        fetchDetailFailed: '获取反馈详情失败:',
        boundEcAccounts: '绑定的 EC 账号',
        title: '反馈中心',
        allFeedback: '全部反馈',
        mySubscriptions: '我的订阅',
        settings: '设置',
        searchPlaceholder: '搜索反馈...',
        noFeedback: '暂无反馈',
        noSubscriptions: '暂无订阅',
        anonymousPlayer: '匿名玩家',
        selectAccount: '选取服内账号',
        selectAccountDesc: '从绑定中选取，无论是否有绑定都可选匿名',
        notificationOptions: '通知选项',
        wechat: '微信',
        qq: 'QQ',
        inGame: '服内',
        unboundDisabled: '未绑定',
        qqNotImplemented: '暂未实现',
        noSubscriptionsHint: '您还没有订阅任何反馈，在反馈详情页可以订阅感兴趣的反馈',
        feedbackStatus: '反馈状态',
        officialReply: '官方回复',
        jumpToReply: '跳转',
        save: '保存',
        cancel: '取消',
        floor: '第{floor}楼',
        showOfficialOnly: '官方回复',
        officialReplyIndex: '官方回复目录',
        createPost: '发布反馈',
        createFeedbackTitle: '创建反馈',
        createSuccess: '反馈创建成功',
        isPublic: '是否公开',
        public: '公开',
        private: '私有',
        subscriptions: '订阅列表',
        filterStatus: '筛选状态',
        allStatus: '全部状态',
        replies: '回复列表',
        submitOfficialReply: '提交官方回复',
        completedCannotReply: '该反馈已处理完成，无法继续回复',
        rejectedCannotReply: '该反馈已拒绝，无法继续回复',
        additionIntro: '良言一句三冬暖，恶语伤人六月寒',
        editorSource: '源代码',
        editorPreview: '预览',
        editorAdvanced: '高级',
        editorMdOnly: '仅支持 Markdown 格式，不支持 HTML',
        toolbarBold: '加粗',
        toolbarItalic: '斜体',
        toolbarStrike: '删除线',
        toolbarLink: '链接',
        toolbarUl: '无序列表',
        toolbarOl: '有序列表',
        toolbarQuote: '引用',
        toolbarCode: '行内代码',
        toolbarCodeBlock: '代码块',
        toolbarHr: '分割线',
        toolbarTable: '表格',
        toolbarTablePlaceholder: '列1 | 列2 | 列3',
        status: {
            discussing: '讨论中',
            processing: '处理中',
            completed: '已完成',
            open: '开启',
            closed: '关闭',
            ended: '完成',
        },
        noReplies: '暂无回复',
        filterType: '类型',
        sortOrder: '排序',
        typeAll: '全部',
        typeSuggestion: '建议',
        typeBug: 'BUG',
        sortCreateTime: '创建时间',
        sortLastReplyTime: '最近回复',
        sortHeat: '热度',
        sortBy: '排序方式',
        sortDirection: '排序方向',
        filterOptions: '筛选选项',
        resetFilter: '重置',
        applyFilter: '应用筛选',
        repliesCount: '{count} 条回复',
        reply: '回复 {count}条',
        floorSuffix: '楼',
        replyToFloor: '回复 #{floor}楼',
        replyThis: '回复',
        setFeatured: '设为精华',
        setFeaturedConfirm: '确定将此条设为精华？',
        cancelReply: '取消',
        lastReply: '最后回复',
        noContent: '暂无内容',
        noFeedbackContent: '还没有反馈内容，管理员发布反馈后会显示在这里',
        noMatchingReplies: '暂无符合条件的回复',
        allReplies: '全部回复',
        tag: '标签',
        tagPlaceholder: '标签 如：起床战争',
        tagSaved: '标签已保存',
        typeSaved: '类型已更新',
        editTag: '编辑标签',
        experience: '土豆种子',
        checkin: '签到',
        checkedInToday: '今日已签到，明天再来',
        checkinSuccess: '签到成功，土豆种子 +5',
        dailyReplyRewardTip: '每日首次回复反馈可额外获得 +3 土豆种子',
        checkinModalTitle: '签到与土豆种子',
        seedBalanceLabel: '当前土豆种子',
        seedRulesTitle: '获得规则',
        seedRuleCheckin: '每日签到：+5 土豆种子（每天一次）',
        seedRuleReply: '每日首次回复反馈：+3 土豆种子（每天一次）',
        createdAt: '创建',
        lastReplyAt: '最后回复',
        replyToUser: '回复 {user}',
        // 发言资格相关
        eligibilityNotSet: '请先在反馈设置中绑定 ECID 昵称，才能参与讨论',
        eligibilityUnbound: '您绑定的昵称已解绑，请重新选择账号',
        eligibilityPunished: '您的账号处于处罚状态，无法参与讨论',
        eligibilityLoading: '正在检查发言资格...',
        eligibilityGoSettings: '前往设置',
        eligibilityCannotReply: '无法发言',
        eligibilityRequireEcid: '必须绑定 ECID 才能发言，匿名发言已禁用',
        selectAccountRequireEcid: '请绑定 ECID 账号（已禁用匿名发言）',
        sendReply: '回复',
        attachment: '附件',
        searchResultCount: '搜索到 {total} 条结果',
        totalFeedback: '共 {total} 条反馈',
        sortHighToLow: '从高到低',
        sortLowToHigh: '从低到高',
        sortNewToOld: '从新到旧',
        sortOldToNew: '从旧到新',
    },
    ticketList: {
        recommend: '推荐阅读',
        about: '关于工单和管理的一切，一篇五千字的长文带你了解我们',
        showProgress: '查看工单处理进度',
        progressTitle: '工单处理进度',
        confirmTitle: '确认提交',
        confirmContent1:
            '请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！',
        confirmContent2: '如工单内容涉及欺骗、辱骂，骚扰，无意义内容，将会被系统自动驳回。',
        confirmContent3: '提交工单即代表同意以上内容。',
        newTitle: '标题',
        newTitleIntro: '请填写工单标题（最多20字）',
        titleTooLong: '标题不能超过20字',
        count_waiting_total: '还有{count}条工单未处理完成',
        count_waiting_unassigned: '等待分配: {count}条',
        count_waiting_assigned: '正在处理: {count}条',
        next_tid_vip: 'VIP通道即将分配: TID#{tid}',
        next_tid_normal: '常规通道即将分配: TID#{tid}',
        no_next_ticket_vip: 'VIP通道当前没有待处理工单',
        no_next_ticket_normal: '常规通道当前没有待处理工单',
        player_guidelines: '玩家守则',
        title: '我的工单',
        intro: '欢迎来到工单系统！我们会竭尽全力为您服务。如果您的问题仍未解决且情况严重，请提交"争议仲裁与部门复核"工单。',
        integrity:
            '请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！如工单内容涉及欺骗、辱骂，或对客服回复断章取义，该工单可能会被公示，提交工单即代表同意以上内容。',
        newBtn: '创建工单',
        wikiBinding: 'WIKI绑定申请',
        newIntro:
            '请尽可能详细的描述您遇到的问题，我们会尽快与您联系,将在7个工作日内回复，请耐心等待。',
        backToList: '返回工单列表',
        heroBadge: '服务分类指南',
        heroTitle: '选择最合适的工单类型',
        heroSubtitle: '为了更快地解决问题，请先挑选最贴近您需求的服务类别。',
        heroHighlight: '账号申诉 / 举报反馈 / 商品补发 / 活动提交等问题一站式处理',
        newIntroPublic:
            '请注意：请务必详细描述遇到的问题或疑问，抽象或模糊的描述将无法得到及时的帮助。',
        adminRecruit: {
            before: {
                title: '⏰ 本轮管理员招新申请将在 {countdown} 后开启',
                openTime: '开启时间：{time}',
                closeTime: '关闭时间：{time}',
                intro: '敬请期待！本轮管理员招新申请即将开启，欢迎持续关注 EaseCation 的社群账号，第一时间获取最新动态！',
            },
            open: {
                title: '⏰ 本轮管理员招新申请进行中，将在 {countdown} 后关闭',
                closeTime: '关闭时间：{time}',
                intro: '为了更好地维护和管理服务器，EaseCation管理员职位长期开放申请，希望有更多热爱游戏、热心服务玩家的小伙伴们加入我们的团队，共同为EaseCation的发展贡献力量！',
                preRulesPrefix: '在撰写个人陈述之前，我们建议申请人提前阅读',
                preRulesPlayerGuidelines: '《EaseCation玩家守则》',
                preRulesAnd: '与',
                preRulesGeneralGuidelines: '《EaseCation总则》',
                preRulesMiddle: '，您可以在',
                preRulesWiki: 'EaseCation Wiki',
                preRulesSuffix:
                    '上查阅相关内容。当您提交申请时，您默认授权我们在招新事务上储存和分析您所提供的信息，且同意承担因“虚假信息”所致的一切后果（包括且不限于：驳回申请、加入黑名单及其他处罚）',
                statementIntro: '请用中文撰写一篇个人陈述，要求包含以下内容：',
                statementPart1Prefix: '1. 自我介绍。包括：',
                statementPart1Highlight: '您的法定年龄与QQ联系方式',
                statementPart1Suffix:
                    '、您在EaseCation的游戏经历、您对EC社区的贡献及影响、您希望成为EaseCation管理员的缘由，以及您认为自己足以胜任的原因。',
                statementPart2: '2. 笔试。选择以下至少一个主题进行阐述：',
                topicAPrefix: 'a. EaseCation的管理工作分析：基于',
                topicATitle: '《关于工单和管理的一切》',
                topicASuffix: '，请分析EaseCation的管理工作的优势和不足，并提出您的建议。',
                topicB: 'b. 我的世界作弊端与反作弊系统分析： 请分析当前的我的世界作弊现状以及EaseCation的反作弊系统，提出您的个人看法。',
                topicC: 'c. 请结合您的个人经历，撰写一篇关于您在EaseCation的深度游玩体验的文章。您可以描述您在游戏中的成长历程、与社区的互动、以及您对EaseCation的独特见解和感受。',
                topicD: 'd. 对于最近EaseCation公关事件(刷箱，创作者处罚)如果你是公关，管理团队或者开发者，你怎么看，并怎么处理，你认为ec还有什么要优化。',
                ageLimit:
                    '我们不建议中学阶段的学生申请管理员职位，因为这可能会影响您的学业；我们原则上只接受18岁以上的申请者，但不排除特殊情况。',
                noAi: '请不要使用AI来完成个人陈述，此类申请会被直接拒绝，我们并不要求华丽的词藻，而是更看重您的真诚和实际行动。',
                noSensitiveInfo:
                    '不要在招新文书里面出现个人敏感信息，例如真实姓名，住址和手机号等。',
            },
            closed: {
                title: '🚫 本轮管理员招新申请已关闭',
                notice: '招新管理员招新申请已于 {time} 关闭。欢迎持续关注 EaseCation 的社群账号，第一时间获取最新动态！',
            },
        },
        success: '提交成功 我们将尽快处理',
        clear: '清空',
        clearSuccess: '已清空',
        clearConfirmTitle: '提示',
        clearConfirmContent: '您即将清空当前工单填写的内容，请确认。',
        draftRestored: '草稿已恢复',
        type: '工单类型',
        typeSummary: {
            AP: '管理员申请',
            AG: '账号封禁/禁言自助申诉',
            RP: '举报违规玩家',
            SP: '商城订单/奖励补发',
            AW: '工单账号解冻申请',
            OP: '土豆百事通',
            JY: '反馈中心现已上线',
            RS: '高级审核处理，仅支持当事人争议调解与上诉',
            OT: '其他土豆问题通道',
            ME: '媒体活动提交',
        },
        typeGroups: {
            support: {
                title: '常用服务',
                description: '举报、发货、玩法咨询等常见问题都在这里。',
            },
            security: {
                title: '账号服务',
                description: '处理封禁、解冻及其他账号相关的紧急事项。',
            },
            feature: {
                title: '其他服务',
                description: '针对EC其他问题、媒体活动和管理员申请的专门入口。',
            },
        },
        typeExtra: {
            '': '请选择工单类型',
            AP: '您可以在这里申请成为管理员，但请注意，我们会对您的游戏数据、行为等进行全面审核，以确保您符合成为管理员的条件。',
            AG: '如果您的账号被关进小黑屋或遭到封禁，您可以在这里提交申诉。请详细说明情况，以便我们更快处理。如果是无法绑定或禁言申诉，请提交“其他服务”工单。\n请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！',
            RP: '在这里，您可以举报违规玩家。我们会优先通过EC小法庭进行玩家投票审判，确保裁决的公平性和透明度。\n请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！',
            SP: '如果您在EC商城购买的商品未成功发货，或是在服务器中的各类奖励、商品、邮件附件等未成功领取，我们将在这里帮您核实处理。\n请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！',
            AW: '如果您的工单账号被冻结，您可以在这里申请解冻。但请注意，由于不诚信导致的冻结无法解冻。',
            OP: 'EC wiki为你服务',
            JY: '反馈中心现已上线',
            RS: '高级审核处理，仅支持当事人争议调解与上诉。',
            OT: '如果您的问题不属于以上类别，比如无法绑定账号，请在这里提交，我们会尽快协助您解决。\n请确保您提交的内容均为真实信息。工单系统建立在玩家与客服团队的信任之上，若发现欺骗行为，您的账号可能面临最高 10年封禁 的处罚！',
            ME: '如您参与了媒体团队的相关活动，请按活动指引在此提交工单。',
        },
        account: INITIATOR_LABELS,
        accountNoLongerBound: '您选择的账号已解绑，请重新选择一个已绑定的游戏账号。',
        accountExtra: {
            AP: '请选择您的EC账号',
            AG: '若无法绑定账号，请提交 其他 类型的工单。若账号被冻结，请先提交“工单账号解冻申请”工单',
            RP: '为了防止恶意举报，我们需要您提供您的游戏账号。请放心，我们坚决不会向第三方透露您的账号',
            SP: '请选择您当时下单所使用的EC账号',
            AW: '请选择被冻结的EC账号或工单账号',
            JY: '(选填) 我们可能会给这个账号发送一份奖励',
            RS: '(选填) 我们可能会给这个账号发送一份奖励',
            OT: '(选填) 您可以选择一个与这个工单有关的已绑定游戏账号',
            ME: '请选择一个用于领奖的ECID，该ECID必须已绑定至用户中心。',
        },
        target: TARGET_LABELS,
        targetExtra: {
            RP: '请输入被举报玩家的昵称或ECID，随后在下方选择匹配的玩家',
            RS: '请输入争议事件工单号或相关人员id，方便我们核实处理',
            OT: '(选填) 您可以填写一个EC账号昵称或ECID，随后在下方选择匹配的账号',
        },
        bestMatch: '账号匹配',
        bestMatchIntro:
            '请选择一个依照您提供的账号信息匹配的玩家账号，若没有显示，则代表您输入不正确或没有相关玩家',
        bestMatchPlaceholder: '请输入昵称或ECID进行搜索',
        bestMatchLastLogin: '最后登录：',
        quickInsert: '快速模板',
        activity: '活动',
        activityIntro: '请选择你参与的活动',
        quickInsertIntro: '若您符合某些情况，推荐选择一个快速模板以便一次性给我们提供所需的信息。',
        quickInsertList: {
            DS: '您是否对账号拥有唯一所有权：\n当前是否可以登录账号：\n发现账号被盗时间：\n是否曾出借过账号：\n其他信息：',
            CPS: 'CPS/请通过自助申诉发起业务,其他服务不受理相关信息',
            TEN: 'EaseCation十周年庆 × 六一乐乐乐！\n请按模板填写\n小红书号：\n帖子分享链接：\n截图请在附件提交',
            ECNET_LIKE: '公众号-土豆大礼包\n微信号：\n档期：\n截图请在附件提交',
            ECXHS_POST: '小红书-有奖话题活动\n档期：\n帖子链接：\n截图请在附件提交',
            ECRL_POST:
                'EaseCation 鬼魅圣符前瞻\n请按模板填写\n小红书号：\n帖子分享链接：\n截图请在附件提交',
            ECPYQJ_POST: 'EaseCation 片羽寄情\n请按模板填写\n对方ECID：\n帖子分享链接：',
            OTHER: '请按活动指引补充信息，并配合客服问询。',
        },
        quickInsertListTitle: {
            DS: '被盗号导致长时间封禁',
            CPS: '其他服务不受理相关信息',
            TEN: '十周年',
            ECNET_LIKE: '公众号-土豆大礼包',
            ECXHS_POST: '小红书-有奖话题活动',
            ECRL_POST: '圣符传说',
            ECPYQJ_POST: '片羽寄情',
            '8DAY8MAP': '八天八图寻彩蛋',
            OTHER: '其他活动',
        },
        xhsId: '小红书号',
        xhsIdPlaceholder: '请输入小红书号',
        wechatId: '微信号',
        wechatIdPlaceholder: '请输入微信号',
        schedule: '档期',
        schedulePlaceholder: '请输入档期',
        targetEcid: '对方昵称或ECID',
        targetEcidPlaceholder: '请输入对方昵称或ECID',
        postLink: '帖子分享链接',
        postLinkPlaceholder: '请输入帖子分享链接，若没有则填无',
        mediaId: '媒体序号',
        mediaIdPlaceholder: '请输入您的媒体ID',
        screenshotNote: '截图请在附件提交',
        notstarttime: '活动未开始',
        endtime: '活动已结束',
        remark: '详细信息！',
        details: '详细信息',
        detailsExtra: {
            '': '详细信息',
            AP: '您的个人陈述，请务必包含上文提到的信息，我们推荐您在附件中上传PDF格式文件，图文并茂地阐述您的观点。',
            AG: '详细描述您被处罚时的情况，帮助我们更全面地了解问题。请务必诚信提交，以便我们更快帮您核实处理。',
            RP: '请描述您是在哪发现的违规行为，以及为什么认为 TA 在作弊，提供尽可能多的细节会帮助我们更精准判断。请务必提供相关视频/回放号/截图,及具体违规行为，否则将被系统审核失败驳回！\n如果该内容在判定违规时无法达成一致，我们会将该情况加入监管系统进行进一步核查!。由于管理权限必须受到严格限制，对于争议较大的案件，我们会让玩家群体通过监管系统来共同参与决策，确保裁决的客观性与公正性！',
            SP: '请提供一些订单相关信息，比如购买时间、消费金额等，并记得上传购买截图，以便我们更快帮您核实！我们推荐您录制视频来佐证。',
            AW: '请告诉我们您是何时发现被冻结的，以及其他可能有帮助的信息，反思您被冻结的原因，可能有利于更快解冻。',
            OP: '有任何疑问尽管提问！我们会认真解答您的问题。',
            JY: '您的意见和建议对我们很重要！欢迎畅所欲言，帮助我们优化体验。提交工单后，系统可能会根据大家的建言情况大数据自动生成创建反馈中心帖子，与开发团队亲密交流！',
            RS: '请务必详细描述情况，并提供相关证据，以便我们更好地理解和处理您的诉求。如果只提交存在异议的工单号而不详细说明具体情况，可能会被直接驳回。',
            OT: '请具体描述您的问题或需要我们帮助的内容，提供更多细节能让我们更快处理哦！',
            ME: '请按模板指引补全信息，请勿更改模板内容。',
        },
        happenedDate: '发生日期',
        happenedDateExtra: '请填写事件发生的时间（大致即可）',
        happenedTime: '大致时间',
        gameMode: '发生位置（游戏模式）',
        gameModeExtra: '请选择违规玩家所在的游戏模式',
        selectGameMode: '请选择游戏模式',
        attachments: '附件',
        attachmentsExtra:
            '最多十个100MB以下的图片/视频/PDF，请上传后等待上方文件上传完毕指示弹出后，再点击下方提交按钮，否则附件会消失！',
        submit: '提交',
        mediaStatusError: {
            noMediaAccount: '请在媒体中心注册媒体账号',
            invalidMediaStatus: '您的媒体账号已经被冻结',
            pendingMediaTicket: '请等待正在处理中的媒体工单处理完成',
            goToMediaCenter: '前往媒体中心',
        },
    },
    ticketDetail: {
        addition: '回复消息',
        additionIntro: '您可以在此向客服提供更多信息',
        attachment: '附件',
        attachmentIntro: '最多十个100MB以下的图片/视频/PDF',
        submit: '回复',
        success: '回复成功',
        drop: '撤销工单',
        dropConfirm: '确认撤销工单吗？',
        dropInto: '撤销后将无法恢复',
        dropSuccess: '工单已撤销',
        dropConfirmY: '确认撤销',
        dropConfirmN: '我再想想',
        revoke: '撤回',
        revokeConfirm: '确认撤回这条回复吗？',
        revokeConfirmTitle: '撤回回复',
        revokeSuccess: '回复已撤回',
        revokeFailed: '撤回失败',
        revokedMessage: '撤回消息',
        internalNote: '内部备注',
        noteLabel: '备注',
        editNote: '编辑',
        convertToReply: '转为用户可见',
        editNoteSuccess: '内部注释已更新',
        editNoteFailed: '编辑失败',
        convertToReplySuccess: '已转为用户可见',
        convertToReplyFailed: '转为用户可见失败',
        convertToReplyConfirm: '确定将这条内容转为用户可见吗？',
        convertToReplyConfirmTitle: '转为用户可见',
        clickToAddClue: '你可以点击进入并补充更多线索',
        issueTracked: '此问题已被记录和跟踪:',
        aiDraftApplied: 'AI草稿已应用到回复框',
        replyCardTitle: '回复工单',
        aiConfirmTitle: '确认执行AI操作建议',
        aiConfirmOk: '确认执行',
        aiConfirmContent: '您确定要执行这个AI建议的操作吗？',
    },
    ticket: {
        none: '无',
        fetchMediaFailed: '获取媒体信息失败:',
        durationDhms: '{days}天 {hours}小时 {minutes}分钟 {seconds}秒',
        dateTimeFormat: 'YYYY年MM月DD日 HH:mm:ss',
        process:
            '您好，您的工单已处理完成啦！感谢您的支持与配合~ 如果对我们的服务有任何意见，欢迎再次提交该类型的工单并提供工单序号 {tid}，若您对此次工单有任何异议，可以通过“争议仲裁与部门审核”工单申请复核，我们的主管团队一定会继续跟进，需要其他帮助也欢迎随时再找我们，记得提供本次工单号方便我们查询记录哦！',
        reject: '很抱歉这次没能帮到您，当前工单提供的信息不足以处理。如果您认为处理结果有误，请先尝试重新提交原类型工单。若异议依然存在，可以通过“争议仲裁与部门审核”工单申请复核，我们会由高级仲裁部门进行全面核查，但需要一定时间。后续如需其他协助，新建工单时请备注本次编号 {tid}~',
        revocation: '该工单已由发起方主动撤回。希望下次能有机会为您效劳！(๑•̀ㅂ•́)و✧',
        entrust: '该工单正在被转交到专人客服处理',
        TID: 'TID# ',
        initiate: '发起工单',
        assigned: '已分配客服',
        reassign: '已升级处理优先级',
        completed: '完成',
        submitter: '提交人',
        target: '目标',
        status: TICKET_STATUS_NAME_MAP,
        type: TICKET_TYPE_NAME_MAP,
        priority: {
            15: '高级专员通道',
            25: '账号冻结通道',
            27: '申请E点通道',
            28: '媒体审核通道',
            33: '创作者快速通道',
            35: '创作者普通通道',
            43: 'VIP 4 专属通道',
            44: 'VIP 3 专属通道',
            95: '常规通道',
        },
    },
    ticketOperate: {
        addition: '回复工单',
        success: '回复成功',
    },
    ticketAnonymity: {
        openInWorkshop: '在管理中心打开',
    },
    adminPermission: {
        insufficient: '权限不足，无法访问此页面',
    },
    common: {
        cancel: '取消',
        confirm: '确认',
        modified: '已修改',
        success: '成功',
        failed: '失败',
        skipped: '跳过',
        create: '创建',
        save: '保存',
        saved: '已保存',
        copy: '复制',
        download: '下载',
        back: '返回',
        copySuccess: '已复制到剪贴板',
        copyFailed: '复制失败，请重试',
        delete: '删除',
        unknown: '未知',
        noData: '暂无数据',
        prevPage: '上一页',
        nextPage: '下一页',
        close: '关闭',
        submit: '提交',
        switch: {
            open: '开启',
            close: '关闭',
        },
        internal_server_error: '内部服务器错误',
        submitting: '提交中...',
        errorLabel: '错误：',
    },
    time: {
        unknown: '未知时间',
        invalid: '无效时间',
        justNow: '刚刚',
        secondsAgo: '{n}秒前',
        minutesAgo: '{n}分钟前',
        hoursAgo: '{n}小时前',
        daysAgo: '{n}天前',
        monthsAgo: '{n}个月前',
        yearsAgo: '{n}年前',
    },
    form: {
        requiredField: '此字段为必填项',
        selectUserFromDropdown: '请从下拉列表中选择用户',
        userNotFound: '未找到匹配的用户',
        selectUser: '请选择用户',
        wikiSearching: '正在搜索用户ID，请稍候...',
        wikiUseridNotFound: '未找到匹配的用户ID，请检查用户名是否正确',
        wikiUseridRequired: '必须获取到WIKI用户ID才能提交',
        wikiUseridMustBePositive: 'WIKI用户ID必须是有效的正整数',
        searching: '搜索中...',
    },
    pageMeta: {
        defaultTitle: '用户中心',
        defaultDescription: 'EaseCation用户中心 - 工单系统',
        titleWithSuffix: '{pageTitle} - 用户中心',
    },
    feedbackEligibility: {
        checkFailed: '检查反馈发言资格失败:',
        mustUseInProvider: 'useFeedbackEligibility 必须在 FeedbackEligibilityProvider 内使用',
    },
    accountRecovery: {
        recoverFailed: '找回账号失败:',
        emailPlaceholder: '请输入邮箱地址',
        emailInvalid: '请输入有效的邮箱地址',
        ecidPlaceholder: '请输入ECID',
        ecidMinLength: 'ECID长度至少3位',
    },
    accountManagement: {
        fetchAccountFailed: '获取账号数据失败:',
        emailUpdateSuccess: '邮箱修改成功',
        emailUpdateFailed: '更新邮箱失败:',
        emailUpdateFailedRetry: '邮箱修改失败，请稍后重试',
        invalidEmailFormat: '邮箱格式不正确',
        missingEcid: '缺少 ECID 参数',
        verifyEmailSentSet:
            '验证邮件已发送，请点击链接完成设置，若未收到请查看垃圾邮件与广告邮件。',
        verifyEmailSentClear:
            '验证邮件已发送，请点击链接完成清除，若未收到请查看垃圾邮件与广告邮件。',
        verifyEmailSentReset:
            '验证邮件已发送，请点击链接完成重置，若未收到请查看垃圾邮件与广告邮件。',
        seconds: '60秒',
        setSecurityEmailFailed: '设置密保邮箱失败:',
        clearSecurityEmailFailed: '清除密保邮箱失败:',
        resetPasswordFailed: '重置密码失败:',
        unbindTicketFailed: '解绑工单失败:',
        operationFailedRetry: '操作失败，请稍后重试',
        changePasswordFailed: '修改密码失败:',
        redirectingToPassword: '正在跳转到密码设置页面...',
    },
    playerBinding: {
        queryBindingFailed: '查询绑定信息失败:',
        queryBindingFailedShort: '查询绑定信息失败',
        invalidXuid: '无法获取有效的XUID',
        unbindFailed: '解绑失败:',
        unbindAllFailed: '解绑全部账号失败:',
    },
    playerDetails: {
        permanent: '长期',
    },
    annualReport: {
        ticketTypePermission: '权限审核',
        ticketTypeAppeal: '处罚申诉与减罚申请',
        sectionBasic: '基础信息',
        sectionLogin: '登录统计',
        sectionGame: '游戏统计',
        sectionRank: '段位数据',
        sectionCurrency: '货币数据',
        sectionSocial: '社交数据',
        sectionTicket: '工单统计',
        sectionAI: 'AI评价',
        sectionTitle: '年度称号',
        ecidMissing: 'ECID参数缺失',
        fetchPlayerNameFailed: '获取玩家名称失败:',
        fetchTypeDataFailed: '获取{type}数据失败:',
        fetchBasicFailed: '获取基础信息失败，请稍后重试',
        gameBedwars: '起床战争(水晶战争)',
        unknown: '未知',
        rankCrystal: '璀璨凝晶',
        rankBedrock1: '基岩 I',
        rankBedrock2: '基岩 II',
        rankBedrock3: '基岩 III',
        rankBedrock4: '基岩 IV',
        rankDiamond1: '钻石 I',
        rankDiamond2: '钻石 II',
        rankDiamond3: '钻石 III',
        rankDiamond4: '钻石 IV',
        rankGold1: '黄金 I',
        rankGold2: '黄金 II',
        rankGold3: '黄金 III',
        rankGold4: '黄金 IV',
        rankIron1: '铁锭 I',
        rankIron2: '铁锭 II',
        rankIron3: '铁锭 III',
        rankIron4: '铁锭 IV',
        rankCoal1: '煤炭 I',
        rankCoal2: '煤炭 II',
        rankCoal3: '煤炭 III',
        rankCoal4: '煤炭 IV',
        rankCharcoal1: '木炭 I',
        rankCharcoal2: '木炭 II',
        rankCharcoal3: '木炭 III',
        rankCharcoal4: '木炭 IV',
        rankUnranked: '未定级',
        none: '无',
        ecPlayer: 'EC玩家',
        fetchYearSummaryFailed: '获取年度总结数据失败:',
        fetchYearSummaryFailedShort: '获取年度总结数据失败',
        regenerateFailed: '重新生成失败',
        regenerateFailedRetry: '重新生成失败，请稍后重试',
        regenerateAIFailed: '重新生成AI评价失败:',
        calcTitleFailed: '计算称号失败',
        calcTitleFailedRetry: '计算称号失败，请稍后重试',
        confirmClaimTitle: '确认领取年度称号',
        confirmClaim: '确认领取',
        claimSuccess: '年度称号领取成功！',
        claimFailed: '领取失败',
        claimTitleFailed: '领取称号失败:',
        claimFailedRetry: '领取失败，请稍后重试',
        shareTypeRequired: '请至少选择一个分享类型（基础信息为必选项）',
        shareTypeRequiredShort: '请至少选择一个分享类型',
        validHoursRequired: '请填写有效的时限（小时）',
        regenerating: '正在重新生成...',
        regenerateAI: '重新生成AI评价',
        generatingShareLink: '正在生成分享链接和图片...',
        shareLinkFailed: '生成分享链接失败',
        shareLinkFailedShort: '分享链接生成失败',
        yearTitleDataMissing: '年度称号数据缺失',
        modelRenderSuccess: '重新渲染3D模型成功，图像大小:',
        modelRenderFailed: '重新渲染3D模型失败:',
        logoLoadFailed: 'Logo 加载失败:',
        canvasCreateFailed: '无法创建画布',
        fontLoadFailed: '字体加载失败，使用备用字体:',
        player: '玩家',
        yearTitleSuffix: '的2025 年度称号',
        totalGames: '总场次',
        favoriteMode: '本命模式',
        ecVeteran: 'EC老兵',
        aiReviewTitle: '✨ AI年度评价',
        reportTitle2025: 'EaseCation 2025 年度报告',
        scanQRHint: '(扫描二维码查看我的年度报告)',
        modelImageSuccess: '模型图像加载成功，尺寸:',
        modelImageFailed: '模型图像加载失败:',
        modelImageFailedRetry: '模型图像加载失败，请重试',
        modelDrawSuccess: '3D模型绘制成功，位置:',
        modelDrawSize: '尺寸:',
        modelDrawFailed: '绘制3D模型图像失败:',
        modelDataInvalid: '3D模型图像数据无效:',
        generateShareFailed: '生成分享内容失败:',
        generateShareFailedShort: '生成分享内容失败',
        linkCopied: '链接已复制到剪贴板',
        copyFailed: '复制失败:',
        copyFailedManual: '复制失败，请手动复制',
        reportFilename: 'EaseCation_{year}年度报告_{name}.png',
        imageDownloadSuccess: '图片下载成功',
        imageCopied: '图片已复制到剪贴板',
        imageLinkCopied: '图片已作为链接复制到剪贴板',
        copyImageUnsupported: '当前浏览器不支持复制图片到剪贴板',
        copyImageFailed: '复制图片失败:',
        copyImageFailedRetry: '复制图片失败，请重试',
        categoryBedbreak: '拆床',
        categoryBedbreakTitle: '拆床狂魔',
        categoryCombat: '战斗',
        categoryCombatTitle: '战斗大师',
        categorySocial: '社交',
        categorySocialTitle: '社交达人',
        categoryExplore: '探索',
        categoryExploreTitle: '探索者',
        categoryCompetitive: '竞技',
        categoryCompetitiveTitle: '竞技高手',
        categoryCasual: '休闲',
        categoryCasualTitle: '休闲玩家',
        categoryBedwars: '起床',
        categoryBedwarsTitle: '起床战神',
        categorySkywars: '空岛',
        categorySkywarsTitle: '空岛之王',
        categoryPit: 'Pit战士',
        categoryStreak: '连胜',
        categoryStreakTitle: '连胜王',
        categoryWinrate: '胜率',
        categoryWinrateTitle: '胜率之王',
        dateMonthDay: '{month}月{day}日',
        loadingMemories: '正在加载你的易什记忆...',
        loadingMemoriesThird: '正在加载他/她的易什记忆...',
        bedwarsShort: '起床战争',
        skywars: '空岛战争',
        other: '其他',
        unmute: '取消静音',
        mute: '静音',
        skipToKeyword: '跳过到年度关键词',
        openMemory: '开启回忆',
        loading: '加载中...',
        playerTimeAllDay: '你是 EC 的全天候玩家！从清晨到深夜，EC 见证了你的每一刻。',
        playerTimeNight: '你是 EC 的夜猫子！深夜的星光陪伴着你在方块世界的冒险。',
        playerTimeMorning: '你是 EC 的早起鸟儿！清晨的第一缕阳光见证了你与 EC 的相遇。',
        playerTimeLoyal: '你是 EC 的忠实玩家！无论何时，EC 都在等待你的到来。',
        playerTimeLoyal2: '你是 EC 的忠实玩家！每一次登录都是与 EC 的美好相遇。',
        playerTimeThirdAllDay: '他/她是 EC 的全天候玩家！从清晨到深夜，EC 见证了他/她的每一刻。',
        playerTimeThirdNight: '他/她是 EC 的夜猫子！深夜的星光陪伴着他/她在方块世界的冒险。',
        playerTimeThirdMorning: '他/她是 EC 的早起鸟儿！清晨的第一缕阳光见证了他/她与 EC 的相遇。',
        playerTimeThirdLoyal: '他/她是 EC 的忠实玩家！无论何时，EC 都在等待他/她的到来。',
        playerTimeThirdLoyal2: '他/她是 EC 的忠实玩家！每一次登录都是与 EC 的美好相遇。',
        thatDayBond: '那一天，你与 EC 的羁绊最深。',
        thatDayBondThird: '那一天，他/她与 EC 的羁绊最深。',
        calculating: '计算中...',
        claimBtn: '🏆 领取我的年度称号',
        claimed: '✅ 已领取年度称号',
        shareReport: '分享年度报告',
        shareReportBtn: '🎁 分享年度报告',
        generating: '生成中...',
        deviceHint: '设备提示',
        swipeUp: '上滑继续',
        hours: '小时',
        shareImageTitle: '年度报告分享图',
        yearSuffix: '年',
        missingShareToken: '缺少分享token',
        fetchShareFailed: '获取分享数据失败',
        fetchShareFailedShort: '获取分享数据失败:',
        skip: '跳过',
        reportHeading: '玩家年度报告',
        desktopResolutionHint: '当前设备分辨率可能观感不佳，建议使用移动端设备进行观看。',
        desktopSwipeHint: '电脑端可通过直接点击"上滑继续"实现翻页。',
        gotIt: '我知道了',
        generateShareLinkButton: '生成分享链接和图片',
        backToHome: '返回首页',
        sharePageTitle: '2025\nEaseCation\n玩家年度报告',
        thirdPersonYearWins: '这一年，他/她在 {mode} 中胜利了 {count} 场',
        thirdPersonFavoriteMode: '他/她的本命模式是',
        thirdPersonMaxKills: '他/她的单场最高击杀记录是 {count} 杀',
        noRankYet: '还没有段位记录，快去排位赛证明自己吧！',
        mostUsedMap: '最常用地图',
        overwatchCount: '被监管',
        unitCount: '个',
        versusMode: '竞技模式',
        casualMode: '休闲模式',
        scoreLabel: '分数',
        dateLabel: '日期',
        onlineDurationLabel: '在线时长',
        longestOnlineTitle: '最长在线记录',
        longestOnlineDesc: '那一天，他/她在 EC 停留了最久。',
        combatDailyTitle: '战斗狂人的日常',
        combatDailyDesc: '他/她的每一场战斗，都在书写传奇。',
        rankRoadTitle: '竞技之路',
        rankRoadDesc: '他/她的段位，见证他/她的成长。',
        withEC: '陪伴EC',
        cumulativeKills: '累积击杀',
    },
    thinkingTimeline: {
        stepStart: '开始',
        stepDecision: '决策判断',
        stepScript: '脚本处理',
        stepAppCustom: '智能分析',
        stepVariableHandle: '变量处理',
        stepAppRefer: '智能体调用',
        stepEnd: '结束',
        modelCall: '模型调用:',
        thinking: '正在思考...',
        thinkingTitle: 'AI思考过程',
        preparing: '准备开始思考...',
        noThinking: '暂无思考过程',
        finalAnswerTitle: '最终答案',
        answerPlaceholder: 'AI生成的答案将在这里显示，您可以直接编辑...',
    },
    debug: {
        streamModalRender: '[DEBUG] StreamModalContent渲染:',
        aiStreamStart: '[DEBUG] AIStreamContext: 开始流式请求',
        aiStreamMessage: '[DEBUG] AIStreamContext: 收到消息',
        aiStreamState: '[DEBUG] AIStreamContext: 当前状态',
        contextThinkingStep: '[DEBUG] Context处理thinking_step:',
        contextUpdateStep: '[DEBUG] Context更新现有步骤 [{existingIndex}]: {stepName}',
        contextAddStep: '[DEBUG] Context添加新步骤: {stepName}',
        contextThinkingDone: '[DEBUG] Context思维步骤处理完成，总数: {count}',
        contextFinalAnswer: '[DEBUG] Context处理final_answer:',
        contextFinalAnswerDone: '[DEBUG] Context final_answer处理完成',
        contextStateDone: '[DEBUG] Context状态更新完成:',
        aiStreamDone: '[DEBUG] AIStreamContext: 流式请求完成',
        aiStreamError: '[DEBUG] AIStreamContext: 流式请求出错',
        useAIStreamStart: '[DEBUG] useAIStream: 开始流式请求',
        useAIStreamMessage: '[DEBUG] useAIStream: 收到消息',
        useAIStreamState: '[DEBUG] useAIStream: 当前状态',
        handleThinkingStep: '[DEBUG] 处理thinking_step:',
        updateExistingStep: '[DEBUG] 更新现有步骤 [{existingIndex}]: {stepName}',
        addNewStep: '[DEBUG] 添加新步骤: {stepName}',
        thinkingStepsDone: '[DEBUG] 思维步骤处理完成，总数: {count}',
        handleFinalAnswer: '[DEBUG] 处理final_answer:',
        finalAnswerDone: '[DEBUG] final_answer处理完成',
        useAIStreamDone: '[DEBUG] useAIStream: 流式请求完成',
        useAIStreamError: '[DEBUG] useAIStream: 流式请求出错',
    },
    aiStream: {
        parseThinkingContent: '[parseThinkingStep.content] 内容:',
        processing: '处理中',
        parseThinkingFailed: '解析思维步骤失败:',
        rawData: '原始数据:',
        thinkingParseFailed: '[DEBUG] 思维步骤解析失败或缺少 onMessage 回调',
        finalAnswerParseFailed: '[DEBUG] 最终答案解析失败或缺少 onMessage 回调',
        dashScopeJsonFailed: '[DEBUG] 百炼响应JSON解析失败:',
        dataPreview200: '数据前200字符:',
        tryOldFormat: '[DEBUG] 尝试作为旧格式解析',
        oldFormatSuccess: '[DEBUG] 旧格式解析成功',
        oldFormatFailed: '[DEBUG] 旧格式解析也失败:',
        notJsonSkip: '[DEBUG] 数据格式不是JSON，跳过:',
        nonDataSseSkip: '[DEBUG] 非data类型的SSE数据，跳过:',
        noAuthToken: '未找到认证token',
        emptyBody: '响应体为空',
        requestCancelled: '请求被取消',
        streamRequestFailed: '流式请求失败:',
    },
    ticketMeta: {
        unknownType: '未知类型',
        unknownStatus: '未知状态',
        statusLabel: ' | 状态: {statusName}',
        ticketSnapshot: ' | 工单快照',
    },
    parseDuration: {
        halfYear: '半年',
    },
    passwordUtils: {
        digestLengthError: '摘要长度异常',
    },
    openLink: '打开链接',
    adminPageMeta: {
        defaultTitle: '管理后台 - 用户中心',
        defaultDescription: 'EaseCation用户中心管理后台',
        titleWithSuffix: '{pageTitle} - 管理后台',
    },
    login: {
        title: '用户中心',
        fetchPageFailed: '获取登录页面失败:',
        wechat: '微信登录',
        qq: 'QQ登录',
        intro: '欢迎使用EaseCation用户中心！',
        jwt: {
            empty: 'JWT不能为空',
            saved: 'JWT已保存',
            saveFailed: '保存JWT失败',
            saveFailedReason: '保存JWT失败:',
            login: 'JWT登录',
            confirm: '确认',
            cancel: '取消',
            placeholder: '请输入JWT令牌',
            linkCopiedWechat: '链接已复制，请在微信中打开',
            copyFailedManual: '复制失败，请手动复制',
            copyFailed: '复制失败:',
            openInWechat: '请在微信中打开',
            openInWechatDesc:
                '微信登录需要在微信浏览器中打开。请复制下方链接，然后在微信中打开此页面。',
            copyLink: '复制链接',
        },
        callback: {
            loading: '正在处理登录...',
            error: '登录失败，请重试',
            errorShort: '登录失败:',
            redirecting: '即将跳转到登录页面...',
        },
    },
    emailVerificationService: {
        sendFailedRetry: '邮件发送失败，请稍后重试',
        sendVerifyFailed: '发送邮件验证失败:',
        verifyTokenFailed: '验证邮件token失败:',
    },
    home: {
        fetchAccountListFailed: '获取账号列表失败',
        selectGameAccount: '选择游戏账号',
        noBoundGameAccount: '你还没有绑定游戏账号',
        goBindGameAccount: '前往绑定账号',
    },
    mainLayout: {
        ecidDetail: '{ecidValue}详情',
        success: '成功',
        logoutSuccess: '退出登录成功',
        logoutFailed: '登出失败:',
        logoutFailedRetry: '登出失败，请重试',
        switchToAdminCenter: '切换到管理中心',
    },
    maintenance: {
        message: '系统维护中',
        subTitle: '系统正在进行维护升级，请稍后再试。',
        contactAdmin: '如有紧急问题，请联系管理员。',
    },
    mediaTicket: {
        fetchUserFailed: '获取用户信息失败',
        apiError: 'API返回错误: {message}',
        requestFailed: '请求失败: {error}',
        enterUidNumber: '请直接输入UID数字',
    },
    monthlyLink: {
        convertBilibiliShortFailed: '转换B站短链接失败',
    },
    document: {
        loadFailed: '# 加载失败\n\n无法读取远程文档，请稍后重试。',
    },
    lotteries: {
        searchPlaceholder: '搜索当前抽奖箱内容...',
        searchResultCount: '找到 {count} 个结果',
        searchResultCountWithCurrent: '找到 {count} 个结果 ({current}/{total})',
        prevResult: '上一个',
        nextResult: '下一个',
        noMatchedResult: '未找到匹配结果',
    },
    publicSgmatch: {
        peopleSuffix: '人)',
    },
    wikiBinding: {
        codeSuccess: '验证码获取成功',
        codeFailed: '获取验证码失败',
        getCode: '获取绑定验证码',
        codeLabel: '验证码',
        ecidLabel: 'ECID:',
        verificationCodeLabel: '验证码:',
        getCodeButton: '获取验证码',
        modalDesc: '选择ECID后，系统将为您生成一个验证码，用于在Wiki系统中完成账号绑定。',
    },
    axios: {
        accountFrozen: '您的账号已被冻结，无法使用此功能',
    },
    systemMessage: {
        riskControl: '系统风险控制',
        aiPrompt: 'AI系统提示',
        applyToReply: '应用到回复',
        executeAction: '执行操作',
    },
    crossDomain: {
        switchFailed: '切换失败',
        switchFailedRetry: '切换失败，请稍后重试',
    },
    videoPlayer: {
        playFailed: '播放失败:',
        playFailedHint: '视频播放失败，请尝试下载后播放',
        loadError: '视频加载错误',
        formatHint: '视频格式可能不兼容当前浏览器，请尝试下载后播放',
        downloadVideo: '点击下载视频',
        unsupportedBrowser: '您的浏览器不支持视频播放',
    },
    feedbackReply: {
        highlight: '精华',
    },
    admin: {
        switchToUserCenter: '切换到用户中心',
        switchToAdmin: '切换到管理中心',
        message: '消息',
        operation: '操作',
        fillPunishTime: '填处罚时间',
        announcementCreated: '公告创建成功',
        announcementServerError: '内部服务器错误',
        announcementSearchPlaceholder: '请输入{field}',
        feedbackCreateFailed: '创建反馈失败:',
        feedbackAdvancedFilter: '高级筛选',
        feedbackTotalCount: '共 {t} 条反馈',
        feedbackRefresh: '刷新',
        feedbackFetchDetailFailed: '获取反馈详情失败:',
        feedbackDeleteFailed: '删除反馈失败:',
        feedbackMarkFailed: '标记状态失败:',
        feedbackTidMissing: 'TID参数缺失',
        mediaListStatus: '状态',
        mediaListExpire: '有效期',
        mediaListEpoint: 'E点',
        mediaListRemark: '备注',
        mediaListAccount: '媒体账号',
        mediaListLink: '主页链接',
        mediaListLastReview: '上次月审日期',
        mediaListCreateTime: '创建时间',
        mediaListTitle: '媒体用户列表',
        mediaListExportFilename: '媒体用户列表_{date}.xlsx',
        mediaListExportSuccess: '导出成功！',
        mediaListExportFailed: '导出失败:',
        mediaListExportFailedRetry: '导出失败，请重试',
        mediaListExportButton: '导出Excel',
        mediaListSearchPlaceholder: '请输入{field}',
        mediaFormatDateFailed: '格式化日期失败: {dateValue}',
        mediaTicketDetailFailed: '获取工单详情失败:',
        editInfo: '编辑信息',
        wikiBindingListUserId: 'WIKI用户ID',
        wikiBindingListUsername: 'WIKI用户名',
        wikiBindingListStatus: '绑定状态',
        wikiBindingListBindTime: '绑定时间',
        wikiBindingListUnbindTime: '解绑时间',
        wikiBindingListTitle: 'WIKI绑定列表',
        wikiBindingListExportFilename: 'WIKI绑定列表_{date}.xlsx',
        wikiBindingListExportSuccess: '导出成功！',
        wikiBindingListExportFailedRetry: '导出失败，请重试',
        panelDurationExample: '例如：1h、1d、1m、1a、半年、2.5a2.5m2.5d',
        banKickLobby: '踢出大厅',
        banYes: '是',
        banNo: '否',
        banGame: '游戏',
        banScoreType: '分数类型',
        banDurationType: '期限类型',
        banRank: '排名',
        banScore: '分数',
        basicLongTerm: '长期',
        basicFrozen: '已冻结',
        basicNormal: '正常',
        mailUnread: '未阅读',
        recordingStartDate: '开始日期',
        recordingEndDate: '结束日期',
        recordingPlayers: '当局玩家',
        ticketAsTarget: '作为 目标',
        ticketAsInitiator: '作为 发起人',
        ticketOpenidPanel: 'OpenID面板 - {openid}',
        ticketOpenidInfo: 'OpenID信息',
        ticketAiApplied: 'AI草稿已应用到回复框',
        ticketReply: '回复工单',
        ticketReplyTitleSelector: '.ant-card .ant-card-head-title:contains("回复工单")',
        ticketConfirmAiAction: '确认执行AI操作建议',
        ticketConfirmExecute: '确认执行',
        ticketConfirmAiContent: '您确定要执行这个AI建议的操作吗？',
        ticketClickHint: '你可以点击进入并补充更多线索',
        ticketAiAnswerPlaceholder: 'AI生成的答案将在这里显示',
        ticketAiAnswerSelector: 'textarea[placeholder*="AI生成的答案将在这里显示"]',
        ticketDebugContent: '[DEBUG] 从TextArea获取的内容:',
        ticketDebugContext: '[DEBUG] 使用Context中的内容:',
        ticketDebugSetField: '[DEBUG] 已设置表单字段值:',
        ticketDebugRender: '[DEBUG] AIGenerateButtonInternal 渲染:',
        ticketIdMissing: '工单ID不存在',
        ticketAiThinkingTitle: '🤖 AI思考和生成过程',
        ticketCancelGenerate: '取消生成',
        ticketClose: '关闭',
        ticketUseReply: '使用此回复',
        ticketInvalidId: '无效的工单ID',
        ticketDebugStreamStart: '[DEBUG] 开始流式生成，工单ID:',
        ticketDebugPrompt: '提示词:',
        ticketAiGenerateFailed: '[ERROR] AI生成失败:',
        ticketLoadDetailFailed: '加载工单 {tid} 详情失败:',
        ticketAiFailed: 'AI生成失败:',
        ticketRematchFailed: '重新AI匹配失败:',
        ticketSubscribeFailed: '订阅失败:',
        ticketFormValidateFailed: '表单验证失败:',
        feedbackEditHighlight: '精华',
        feedbackEditLoadFailed: '加载失败',
        feedbackEditSaveFailed: '保存失败',
        feedbackEditTitle: '编辑',
        feedbackFormatManage: '管理',
        feedbackFormatService: '客服',
        feedbackFormatDev: '开发',
        feedbackFormatOther: '其他',
        feedbackFormatLoadFailed: '加载反馈详情失败',
        feedbackFormatLoading: '加载中...',
        feedbackFormatDefault: ' (默认)',
        feedbackFormatDefaultSuffix: '{alias} (默认)',
        feedbackMetaOpen: '开启 (O)',
        feedbackMetaClose: '关闭 (R)',
        feedbackMetaEnd: '结束 (P)',
        feedbackMetaSuggestion: '建议',
        feedbackMetaBug: 'BUG',
        feedbackMetaLoadFailed: '加载失败',
        feedbackMetaSaving: '保存中…',
        mediaRelatedTicketsFailed: '获取相关工单失败: ',
        mediaPanelGiveMonthly: '发放月礼包',
        mediaPanelNone: '无',
        mediaPanelEpointInvalid: '请输入有效的E点数量',
        mediaPanelEpointSuccess: 'E点发放成功',
        mediaPanelEpointError: '发放E点发生错误',
        mediaPanelMonthlySuccess: '月礼包发放成功',
        mediaPanelMonthlyError: '发放月礼包发生错误',
        mediaPanelStatusError: '修改用户状态发生错误',
        mediaPanelEpointPlaceholder: '请输入发放的E点数量',
        mediaPanelEpointPositive: 'E点数量必须大于0',
        mediaPanelEpointInteger: 'E点数量必须为整数',
        punishmentUpdateFailed: '更新处罚失败:',
        punishmentFreezeFailed: '冻结失败:',
        punishmentUnfreezeFailed: '解冻失败:',
        punishmentMuteFailed: '禁言失败:',
        punishmentUnmuteFailed: '解除禁言失败:',
        quickMsgInsufficient: '证据不足',
        quickMsgInsufficientBody: '您好！很抱歉，您的证据不足以清晰的说明您的工单需求...',
        quickMsgSupervise: '加入监管',
        quickMsgSuperviseBody: '玩家您好！经过管理团队的商讨...',
        quickMsgDeceptive: '欺骗内容',
        quickMsgDeceptiveBody: '您好！经核实，您提交的工单存在涉嫌欺骗性内容...',
        quickMsgOffline: '内容已下架',
        quickMsgOfflineBody: '您好！我们这边核实到您提及的内容/活动已经结束下线了呢...',
        quickMsgLife: '生活愉快',
        quickMsgLifeBody: '如果您有更多需要反馈/交流的问题...',
        quickMsgEcidExplain: 'ECID解释',
        quickMsgEcidBody: '玩家您好！这是对独立ECID相关机制的解释...',
        quickMsgInsufficientBodyFull:
            '您好！很抱歉，您的证据不足以清晰的说明您的工单需求，麻烦您补充一下相关证据（最好有视频等等），期待您的回复~^o^/~ ',
        quickMsgSuperviseBodyFull:
            '玩家您好！经过管理团队的商讨，我们认为该违规行为具有不确定性，无法直接做出处罚决定。我们已经将该玩家最近3局对局回放成功纳入了监管系统，交由监管者众审评判！\n管理权力受到严格限制，<span style="color: blue;">处罚必须在证据非常明确的情况下才能被执行。</span>我们将评判的权利交给玩家，是为了让我们在面对具有争议、可疑的玩家行为时能够做出相对公平、客观的处理，提升处理结果的认可度。<span style="color: blue;">我们希望对我们每一个处罚高度负责，尽最大可能减少误判，</span>请您理解我们的决定。\n如您有任何问题或需进一步协助，请随时发起新的工单噢，感谢您的理解与支持！',
        quickMsgDeceptiveBodyFull:
            '您好！经核实，您提交的工单<span style="color: red;">存在涉嫌欺骗性内容（如伪造图片、虚假信息等）。</span>此类行为严重违反了我们的诚信原则，因此我们<span style="color: red;">拒绝继续处理该工单。</span>\n我们始终高度重视诚信与公平，对任何形式的欺骗行为将采取严格措施。若情况属实，我们有权<span style="color: red;">直接封禁您的游戏账号和冻结工单账号。</span>\n如您认为该判定有误，或对此有任何疑问，请提供真实有效的证明材料，我们将重新审核。感谢您的理解与配合！',
        quickMsgOfflineBodyFull:
            '您好！我们这边核实到您提及的内容/活动已经结束下线了呢，您可以继续关注EaseCation的更多活动哦，感谢您的理解！',
        quickMsgLifeBodyFull:
            '如果您有更多需要反馈/交流的问题，欢迎继续提问/发起工单！再次感谢您对<span style="color: yellow;">Ease</span><span style="color: green;">Cation</span>的支持！祝您生活愉快哦~',
        quickMsgEcidBodyFull:
            '玩家您好！这是对独立ECID相关机制的解释\n[1]使用/out前往登录服创建/绑定独立ECUD，其被创建时没有任何数据，也不支持从其它账户转移任何数据。\n[2]解绑独立ECID后，原来的初始ECID数据会恢复，不会消失哦\n[3]由于技术原因，我们暂时不支持在忘记密码时重置独立ECID的密码，小伙伴要牢记密码哦\n[4]非独立ECID没有密码，也不支持账号迁移的哦。您可以使用/ecid查看您的ECID~\n您可以查阅<a href="https://wiki.easecation.net/EaseCation_Wiki:%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BD%93%E7%B3%BB%E5%8F%8A%E6%8C%87%E4%BB%A4%E8%AF%B4%E6%98%8E">《EaseCation 服务器体系及指令说明》</a>了解更多。',
        quickOpsDownloaded: '已下载 {fileName}',
        quickOpsConfirm: '确认',
        quickOpsNoScript: '当前浏览器不支持脚本功能，请在电脑上使用',
        quickOpsNoScriptExec: '当前浏览器不支持脚本执行功能，请在电脑上使用',
        shareGeneratingScreenshot: '正在生成截图...',
        shareScreenshotFailed: '截图生成失败:',
        shareScreenshotFailedShort: '截图生成失败',
        shareFilename: '工单{tid}_{time}.png',
        shareScreenshotSaved: '截图已保存',
        shareLinkIncomplete: '工单信息不完整，无法生成分享链接',
        shareGeneratingLink: '正在生成分享链接...',
        shareGeneratedLink: '生成的分享链接:',
        shareLinkFailed: '生成分享链接失败:',
        shareLinkFailedRetry: '生成分享链接失败，请重试',
        shareLinkCopied: '快照分享链接已复制到剪贴板',
        shareClipboardFallback: 'Clipboard API 复制失败，降级到其他方法:',
        shareExecCopyFailed: 'execCommand 复制失败:',
        shareDomFailed: 'DOM 操作失败:',
        shareCopyManual: '自动复制失败，请手动复制链接',
        shareLongPressCopy: '请长按上方文本并选择「拷贝」进行复制',
        shareCtrlCopy: '请使用 Ctrl+C 或右键复制',
        shareKnow: '知道了',
        shareDownloadScreenshot: '下载完整截图',
        shareDownload: '下载',
        shareScreenshotPreview: '截图并预览',
        shareScreenshot: '截图',
        shareCopySnapshotLink: '复制工单快照链接（允许任何人查看）',
        shareSnapshotLink: '快照链接',
        ticketParseAliasFailed: '解析staff_alias失败:',
        ticketAliasListFailed: '获取别名列表失败:',
        ticketAliasUpdateFailed: '更新工单别名失败:',
        ticketAliasDefaultSuffix: '{alias} (默认)',
        ticketFastActionKai: '开得大',
        ticketAutoJumpFailed: '自动跳转失败:',
        ticketOperationFailed: '操作失败:',
        ticketAiFormatError: 'AI操作建议格式错误，应该是一个数组',
        ticketOpFormatError: '操作格式错误，缺少type或data字段',
        ticketOpSuccess: '操作 {type} 执行成功',
        ticketExecuteAiFailed: '执行AI操作建议失败:',
        ticketAiFormatOrExecFailed: 'AI操作建议格式错误或执行失败',
        ticketAdvancedSearch: '高级搜索',
        ticketNewWindow: '新窗口打开',
        tlgiftOpenidRequired: '请填写 openid 或选择别名',
        entrustSetNoRemindFailed: '设置今日不再提醒失败',
        entrustSetFailed: '设置失败',
        entrustFetchFailed: '获取委托列表错误:',
        entrustFetchError: '获取委托列表发生错误',
        entrustReloadFailed: '重新加载委托列表错误:',
        entrustRequestFailed: '请求失败',
        entrustBatchFailed: '批量操作失败',
        seniorUnassignedLoadFailed: '加载高级专员待分配工单失败:',
        seniorUnassignedToday: '今天',
        seniorUnassigned7d: '近7天',
        seniorUnassigned30d: '近30天',
        todayTicketsType: '类型',
        todayTicketsCount: '数量',
        todayTicketsHourSlot: '{idx}:00 — {val}单',
        todayTicketsTotal: '工单数量：',
        todayTicketsLoading: '加载中...',
        todayTicketsCreateTime: '创建时间',
        todayTicketsStatus: '状态',
        riskApprovalExecuteFailed: '执行处罚失败:',
        riskApprovalLoadFailed: '加载 riskApprovalList 失败',
        riskApprovalSaveFailed: '保存审批列表失败',
        dashboardDurationHms: '{h}小时{m}分{sec}秒',
        dashboardDurationMs: '{m}分{sec}秒',
        dashboardDurationS: '{sec}秒',
        dashboardEntrusting: '全路网委托中',
        dashboardAvgRecent: '平均耗时(近{limit})',
        dashboardPersonalAvg: '个人平均耗时',
        dashboardEntrustAll: '全路网委托',
        dashboardAvg: '平均(近{limit})',
        dashboardPersonal: '个人平均',
        scoreTopBedbreak: '毁床',
        scoreTopDestroy: '摧毁',
        scoreTopCrystal: '摧毁水晶',
        scoreTopScore: '得分',
        scoreTopKill: '击杀',
        scoreTopDeath: '死亡',
        scoreTopPoints: '分数',
        scoreTopTime: '时间',
        scoreTopWin: '胜场',
        scoreTopHeroKill: '英雄击杀',
        scoreTopKillerKill: '杀手击杀',
        scoreTopFinalKill: '最终击杀',
        scoreTopDefendKill: '保卫击杀',
        scoreTopWitherKill: '凋灵击杀',
        scoreTopParkour100: '百格跑酷',
        scoreTopParkourChimney: '烟囱跑酷',
        scoreTopDaily: '日榜',
        scoreTopWeekly: '周榜',
        scoreTopMonthly: '月榜',
        scoreTopYearly: '年榜',
        scoreTopTotal: '总榜',
        timeInvalid: '无效时间',
        timeJustNow: '刚刚',
        time2HoursAgo: '2小时前',
        time3DaysAgo: '3天前',
        timeSecondsAgo: '{n}秒前',
        timeMinutesAgo: '{n}分钟前',
        timeHoursAgo: '{n}小时前',
        timeDaysAgo: '{n}天前',
        timeMonthsAgo: '{n}个月前',
        timeYearsAgo: '{n}年前',
    },
    spec: {
        announcementParseOpen: '应解析 $$$Open("name")$$$ 返回 name',
        announcementNoMatch: '无匹配应返回 null',
        announcementHasCommand: '包含命令应返回 true',
        announcementNoCommand: '不包含应返回 false',
        announcementInRange: '当前时间在 start~end 内且无 dieTime 应返回 true',
        announcementBeforeStart: '当前时间早于 start 应返回 false',
        announcementAfterEnd: '当前时间晚于 end 应返回 false',
        emailVerifySuccess: '成功时应返回 { success: true }',
        emailVerifyEpfNon200: 'EPF_code 非 200 时应返回 { success: false, message }',
        emailVerifyThrow: '请求抛错时应返回 { success: false, message }',
        emailVerifyMessage: '邮件发送失败，请稍后重试',
        emailVerifyResponse: '成功时应返回 response.data',
        emailVerifyWithPassword: '带 newPasswordHash 时应传入 body',
        emailVerifyRequestFail: '请求失败时应抛错',
        parseDurationEmpty: '空字符串应返回 0',
        parseDuration1h: '仅小时 "1h" 应返回 1',
        parseDuration2d: '"2d" 应返回 48',
        parseDuration1m: '"1m" 应返回 720',
        parseDuration1y: '"1y" 应返回 8760',
        parseDurationHalfYear: '"半年" 应返回 180*24',
        parseDurationHalfYearLabel: '半年',
        parseDurationCombo: '组合 "1d2h" 应返回 26',
        parseDurationNumber: '纯数字应解析为小时数',
        parseDurationCase: '大小写不敏感',
        parseDurationSpace: '带空格应 trim',
        announcementApiRequest: '应请求 GET /announcement/list 并返回 response.data',
        staffApiRequest: '应请求 GET /staff/alias 并返回 response.data',
    },
    mediaUser: {
        id: '媒体序号',
        status: '账户状态',
        mpa: '平台账户',
        EBalance: 'E点',
        QQNumber: '绑定QQ',
        link: '主页链接',
        ECID: 'ECID',
        expireDate: '权限过期时间',
        lastReviewed: '上次月审时间',
        createTime: '加入时间',
    },
    announcement: {
        modal: {
            title: '公告提醒',
            close: '关闭',
            no_announcements: '暂无公告',
            history: '历史公告',
            active: '进行中',
            empty: '暂无进行中的公告',
            inactive: '已结束',
            autoShow: '自动弹出',
            startTime: '发布时间',
            endTime: '结束时间',
            popup: {
                options: {
                    any: '自动弹出',
                    day: '每日弹出',
                    week: '每周弹出',
                    never: '新公告弹出',
                },
            },
        },
    },
    mediaAction: {
        monthlyAudit: 'E点申请',
        alreadyAuditedThisMonth: '本月已经月审',
        certInProgress: '申请审核中: ',
        accountFrozen: '您的账号目前已被冻结',
        applyForCertification: 'E点申请',
        doNotProcrastinate: '不要咕咕！',
        noNeedAuditAgain: '本月无需再次月审',
        checkTicketProgress: '您可以前往工单系统查看申请工单进度哦！请耐心等待。',
        contactSupport: '如有疑问请发起工单联系客服',
        joinMediaFamily: '第一次申请需要提供您的媒体账号信息',
        applyShopPermission: '申请E点',
        applyShopPermissionDesc: '申请E点奖励，兑换精美商品！',
        applyEPoints: '申请E点',
        applyEPointsDesc: '申请E点奖励，兑换精美商品！',
    },
    mediaCenter: {
        title: '创作者中心',
        welcomeTitle: '您好！欢迎来到EaseCation创作者中心！',
        welcomeDesc1: '只需制作有关EC社媒视频/图文/直播，即可兑换海量商品！兑换前，请务必先查看《',
        shopGuidelines: '商城守则',
        welcomeDesc2:
            '》，再点击下方“申请创作者”按钮申请哦。若您的视频和个人影响非常出彩，我们将诚邀您参与《',
        creatorProgram: '卓越创作者',
        welcomeDesc3: '》计划。',
        notCreator: '您还不是创作者，请先申请成为创作者。',
        joinGroupDesc: '加入商城交流群，获取最新资讯和交流机会（每月轮换发布尽在其中哦）',
        joinstatus3groupDesc: '请加入卓越创作者群',
        shopTitle: '创作者商城',
        shopDesc: '欢迎来到EaseCation商城，这里有各种精美商品等你来兑换！',
    },
    unbound: '未绑定',
    viewLink: '查看链接',
    noExpiration: '无过期时间',
    notReviewed: '尚未审核',
    mediaPanel: {
        bind: '绑定',
        mediaApplyReview: '媒体申请/月审',
        actions: '操作',
        edit: '修改',
        display: '显示名称',
        media_id: '媒体序号',
        mpa: '媒体账号',
        statusDis: '状态',
        remark: '备注',
        action: '操作',
        status: {
            O: '正常',
            X: '解绑',
            R: '拒绝',
            W: '等待审核',
            Z: '自动解绑',
            F: '冻结',
            1: '土豆创作者',
            2: '土豆创作者',
            3: '卓越创作者',
            4: '冻结',
            5: '等待审核',
            6: '未申请或被拒',
        },
        expire_date: '有效期',
        link: '主页链接',
        create_time: '创建时间',
        lastReviewed: '上次审核',
        ecid: 'ECID',
        EBalance: 'E点',
        validation: {
            numberRequired: '请输入数字',
            max15Digits: '最多15位数字',
        },
        unbind_time: '解绑时间',
        viewPast: '查看历史',
        changeLevel: '操作方式（该操作不影响游戏账号）',
        changeMonth: '有效期（月）',
        send: '操作',
        O: '允许绑定/解冻',
        R: '拒绝绑定',
        F: '冻结',
        viewEpointLogs: '查看E点记录',
        department: {
            general: '综合',
        },
        operation: {
            all: '全部',
        },
        epointLogs: {
            title: 'E点变更记录',
            loadFailed: '加载E点记录失败',
            columns: {
                time: '时间',
                changeType: '类型',
                amount: '变更值',
                balanceAfter: '余额',
                reason: '原因',
                operator: '操作者',
                extra: '详情',
            },
            changeType: {
                purchase: '消费',
                grant: '发放',
                deduct: '扣除',
                expire: '过期清空',
                adjust: '调整',
            },
            noReason: '无',
            purchaseInfo: '兑换 {title} ×{quantity}',
            source: '来源',
            sourceOptions: {
                player: '玩家',
                admin: '管理员',
                system: '系统',
            },
            reasonKeyword: '原因 / 关键字',
            reset: '重置',
        },
    },
    previewTid: {
        title: '快捷查看其他工单',
        tid: '请输入TID',
        submit: '预览',
        preview: '预览',
    },
    floatingHelper: {
        title: '使用说明',
        ok: '我知道了',
    },
    staffAlias: {
        errorCode: {
            // 客服别名相关错误代码映射 (对应后端 ResponseCode)
            6001: 'aliasNotFound',
            6002: 'saveFailed',
            6003: 'saveFailed',
            6004: 'cannotDelete',
            6005: 'cannotDeleteOnly',
            6006: 'uidFormatError',
            6007: 'nameEmpty',
            6008: 'nameTooLong',
            6009: 'saveFailed',
            6010: 'saveFailed',
        },
    },
    sgMatchScore: {
        title: '饥饿游戏 吃饱杯 2025',
        intro: '实时展示所有的对局成绩～ 有异议可随时申诉哦！',
        empty: '比赛还未开始，敬请期待！',
        item: {
            time: '比赛时间',
            type: '房间类型',
            mapName: '地图名称',
        },
        table: {
            player: '玩家',
            kills: '击杀数',
            killScore: '击杀分',
            playersRemainWhenDeath: '存活名次',
            survivalScore: '存活分',
            totalScore: '总分',
        },
    },
    shopAdmin: {
        tools: {
            upload: {
                title: '本地上传图片',
                desc: '选择图片并上传到本地 merchandise 目录，文件名会自动规范化',
                overwrite: '覆盖已存在文件',
                button: '选择图片并上传',
                success: '图片上传成功',
                failed: '图片上传失败',
            },
        },
        label: {
            productName: '商品名称',
            productCategory: '商品分类',
            isVip: '卓越创作者专属',
            isHidden: '是否隐藏',
            itemId: '物品ID',
            price: '价格',
            validTime: '有效时间（秒）',
            totalLimit: '每月总限购',
            monthlyLimit: '每月个人限购',
            globalLimit: '总个人限购',
            permanentLimit: '永久总库存',
            tipnull: '（留空为不限）',
            productDescription: '商品描述',
            imgLink: '图片链接',
            totalPurchase: '用户总购买/总限购',
            currentMonthPurchase: '用户本月购买/月限购',
            totalSales: '总销售量',
            productId: '商品ID',
            hidden: '已隐藏',
        },
        placeholder: {
            productName: '示例: 高级会员套餐',
            productCategory: '示例: ornament',
            itemId: '示例: wings.fushilangchao',
            validTime: '商品参数',
            totalLimit: '留空为不限',
            monthlyLimit: '留空为不限',
            globalLimit: '留空为不限',
            permanentLimit: '留空为不限',
        },
        validation: {
            required: {
                productName: '请输入名称',
                productCategory: '请输入分类',
                isVip: '请选择商品类型',
                itemId: '请输入物品ID',
                price: '请输入价格',
                productDescription: '请输入描述',
            },
            invalid: {
                imgLink: '请输入有效的URL地址',
            },
        },
        option: {
            normalProduct: '普通商品',
            vipProduct: '卓越创作者专属',
            visible: '显示',
            hidden: '隐藏',
        },
        modal: {
            add: { title: '添加新商品' },
            edit: { title: '编辑商品' },
        },
        confirmPurchase: '确认购买',
        orderInformation: '订单信息',
        paymentInformation: '支付信息',
        purchaseQuantity: '购买数量',
        optional: '（选填）',
        pleaseSelectPurchaseQuantity: '请选择购买数量',
        quantityCannotBeLessThan1: '数量不能小于1',
        productSoldOut: '该商品已售罄',
        maxPurchaseQuantityIs: '最大可购买数量为',
        purchaseQuantityExceedsAvailableStock: '购买数量超过可用库存',
        networkRequestException: '网络请求异常',
        soldOut: '已售罄',
        immediatelyPurchase: '立即购买',
        totalQingDianPayable: '应付总E点',
        remainingQingDian: 'E点剩余',
        productUnitPrice: '商品单价',
    },
    shop: {
        priceMustBeInteger: '价格必须为整数',
        recordRange: '{start}-{end} / {total} 条记录',
        recordTotal: '共 {total} 条记录',
        pageSummary: '第 {page} 页，共 {pages} 页',
        title: '创作者商城',
        subtitle: '温馨提示：E点仅当月有效，请尽快兑换',
        welcomeMessage: '欢迎来到EaseCation商城，这里有各种精美商品等你来兑换！',
        all: '全部商品',
        category: {
            deathshow: '击杀秀',
            s7: 'S7',
            pose: '姿势',
            key: '钥匙',
            vip: 'VIP',
            addition: '经验券',
            sw: '空岛战争',
            toy: '小玩具',
            checkin: '月卡',
            pet: '宠物',
            ornament: '4D装扮',
            zb: '粒子效果',
            resourcepack: '材质包',
            prefix: '称号',
            currency: '点券',
            rl: '圣符传说',
            general: '标准',
            mw: '超战',
            activity: '活动',
            parkour: 'parkour',
        },
        maintenance: {
            title: '创作者商城打个小盹儿中～',
            subTitle: '小伙伴们正在补货和擦亮货架，请稍后再来逛逛呀！',
        },
        mediaIDLabel: '媒体ID',
        openIDLabel: 'openID',
        statusLabel: '状态',
        mediaPlatformLabel: '媒体平台',
        EBalanceLabel: 'E点余额',
        QQNumberLabel: 'QQ号',
        homepageLinkLabel: '主页链接',
        gameAccountLabel: '游戏账号',
        permissionValidityLabel: '权限有效期',
        lastReviewedLabel: '上次月审日期',
        createDateLabel: '创建日期',
        productStore: '商品商店',
        searchPlaceholder: '搜索商品名称',
        ascendingOrder: 'E点升序',
        descendingOrder: 'E点降序',
        VIPWarning: '只有卓越创作者才能兑换限定商品！',
        executiveLimit: '卓越创作者限定',
        executiveLimitShort: '卓越限定',
        soldCount: '累计已售',
        soldCountLabel: '累计已售: {count}件',
        globalRemaining: '全局限购',
        fetchFail: '获取商品数据失败',
        searchFail: '搜索失败，请重试',
        noMatchFound: '没有找到匹配的商品，请尝试其他关键词',
        noProduct: '暂无商品，请稍后再来',
        // noProduct: "商品表正在更新，预计7月2日更新完成，请耐心等待",
        noProductInCategory: '当前分类下暂无商品',
        know: '我知道了',
        settlementRules: '结算规则',
        departmentHead: '部门负责人可依据实际情况发放额外的E点点',
        operationScore: '操作总分是服内操作和工单操作数的总和，包括所有类型的操作。',
        totalRemaining: '总剩余',
        monthlyRemaining: '本月剩余',
        permanentRemaining: '永久库存剩余',
        noPurchaseLimit: '无购买限制',
        insufficientPermission: '权限不足，开启商城权限并申请E点审核通过后购买',
        insufficientPermissionButton: '权限不足',
        insufficientBalanceButton: '余额不足',
        pleaseSelectPurchaseQuantity: '请选择购买数量',
        quantityCannotBeLessThan1: '数量不能小于1',
        itemSoldOut: '该商品已售罄',
        maxPurchaseQuantity: '最大可购买数量',
        purchaseQuantityExceedsAvailableStock: '购买数量超过可用库存',
        purchaseSuccess: '购买成功',
        networkRequestException: '网络请求异常',
        confirmPurchase: '确认购买',
        orderInformation: '订单信息',
        paymentInformation: '支付信息',
        purchaseQuantity: '购买数量',
        optional: '（选填）',
        remainingLovePoints: 'E点剩余',
        itemPrice: '商品单价',
        totalLoveCost: '应付总E点',
        soldOut: '已售罄',
        submitting: '提交中...',
        immediatelyPurchase: '立即购买',
        quantityRange: '数量范围：{min}-{max}',
        onlyOnePurchase: '当前只能买一次',
        sort: {
            default: '由新到旧',
            timeAsc: '由旧到新',
            priceAsc: '价格正序',
            priceDesc: '价格倒序',
            salesAsc: '销量正序',
            salesDesc: '销量倒序',
        },
        purchaseLogs: {
            title: '购买记录',
            fetchFailed: '获取购买记录失败',
            onlyAfter: '仅展示 {date} 之后的记录',
            noData: '暂无购买记录',
            columns: {
                time: '时间',
                product: '商品',
                quantity: '数量',
                total: 'E点总消费',
                ecid: 'ECID',
            },
        },
    },
    purchaseLimit: {
        globalTitle: '总个人限购',
        globalDesc: '您总共可购买 {count} 次',
        totalTitle: '每月总限购',
        totalDesc: '全服每月限购 {count} 次',
        monthlyTitle: '每月个人限购',
        monthlyDesc: '您每月可购买 {count} 次',
        permanentTitle: '永久总限购',
        permanentDesc: '全服永久限购 {count} 次',
        soldOutShort: '售罄',
        soldOutTotal: '已售罄',
        soldOutUsedUp: '已用完',
        remainingSuffix: '{count} 剩余',
    },

    documentCenter: {
        title: '文档中心',
        general: {
            title: '总则',
            desc: 'EaseCation 服务器总则',
        },
        media: {
            title: '卓越创作者守则',
            desc: '成为卓越创作者需遵守的相关规定。',
        },
        shop: {
            title: '商城守则',
            desc: '商城兑换、权益相关的详细规则。',
        },
        player: {
            title: '玩家守则',
            desc: '所有玩家应遵守的行为规范。',
        },
        lotteries: {
            title: '抽奖箱概率表',
            desc: '抽奖活动相关的概率表。',
        },
    },
    monthlyLinkVideo: {
        title: 'B站视频信息',
        fetchError: '获取视频信息失败',
        noData: '暂无数据',
        currentWeek: '当周视频',
        notCurrentWeek: '非当周视频',
        currentMonth: '当月视频',
        notCurrentMonth: '非当月视频',
        labels: {
            title: '标题',
            up: 'UP主',
            playCount: '播放量',
            likeCount: '点赞数',
            bvid: 'BV号',
            pubdate: '发布时间',
        },
    },
    resources: {
        title: '更多资源',
        welcomeTitle: '欢迎来到更多资源页面',
        welcomeDesc1: '这里是小可爱工具箱，超多好用资源等你来发现喔~',
        sections: {
            openSource: {
                title: '开源项目',
                description: 'EaseCation 开源社区项目，欢迎 Star 和贡献',
            },
            wiki: {
                title: '知识库',
                description: '开发者文档和游戏百科',
            },
            social: {
                title: '社交媒体',
                description: '关注我们的最新动态',
            },
            tools: {
                title: '实用工具',
                description: '在线工具集合',
            },
        },
        theme: {
            titleShort: '主题',
            title: '主题设置',
            description: '在这里选择页面主题，体验不同的色彩风格～',
            systemLabel: '默认主题',
            systemDescription: '保持现有的浅色 / 深色设计。',
            blackOrangeLabel: '黑橙主题',
            blackOrangeDescription: '深邃黑色、温润白色与活力橙色的对比配色。',
            blackOrangeNote: '启用后页面将自动切换到深色模式。',
            whiteMinimalLabel: '黑白极简主题',
            whiteMinimalDescription: '以纯白背景与深色文字呈现的黑白极简配色。',
            whiteMinimalNote: '启用后页面将自动切换到明亮模式。',
        },
        openSource: {
            eccamera: {
                title: 'ECCamera',
                description: '为《我的世界》中国版设计的高级相机控制Mod，支持电影级相机动画和特效',
                features: ['相机动画路径', '多种插值方式', '景深效果', '晕影效果', '颜色调整'],
                stars: '5',
                language: 'Python',
            },
            mcpywrap: {
                title: 'mcpywrap',
                description: '《我的世界》中国版 ModSDK 包管理工具，简化开发流程',
                features: ['包管理', '项目初始化', '依赖管理', '构建发布', '游戏实例管理'],
                stars: '11',
                language: 'Python',
            },
            fabricrock: {
                title: 'FabricRock',
                description: '轻松将 Minecraft Bedrock 附加包转换为 Fabric 的新视野',
                features: ['Fabric 支持', '模组开发', 'API 接口', '社区驱动'],
                stars: '8',
                language: 'Java',
            },
        },
        wiki: {
            devWiki: {
                title: '开发者 Wiki',
                description: '技术文档、API 参考和开发指南',
                url: 'https://mcwiki.easecation.net/',
            },
            gameWiki: {
                title: '游戏 Wiki',
                description: '游戏攻略、物品百科和社区内容',
                url: 'https://wiki.easecation.net/',
            },
        },
        social: {
            bilibili: {
                title: '哔哩哔哩',
                description: '视频教程和游戏实况',
                handle: '@EaseCation',
            },
            xiaohongshu: {
                title: '小红书',
                description: '游戏攻略和生活分享',
                handle: '@EaseCation',
            },
            wechat: {
                title: '微信公众号',
                description: '最新资讯和活动通知',
                handle: 'EaseCationNet',
            },
            douyin: {
                title: '抖音',
                description: '短视频内容和游戏花絮',
                handle: '@EaseCation',
            },
            qqchannel: {
                title: 'QQ频道',
                description: '官方社区和玩家交流',
                handle: 'EaseCation',
            },
        },
        tools: {
            wikiTools: {
                title: 'Wiki绑定',
                description: '将用户中心账号绑定至EC Wiki',
            },
            textGenerator: {
                title: '3D字生成器',
                description: '在线3D文字生成工具',
            },
            imageProcessor: {
                title: '图片处理器',
                description: '图片硬边缘缩放工具',
            },
            mcTextFormatter: {
                title: 'MC文本格式化工具',
                description: 'Minecraft文本格式化工具',
            },
            github: {
                title: 'GitHub主页',
                description: '访问 EaseCation 的 GitHub 项目主页',
            },
        },
    },
    emailVerification: {
        checkFailed: '检查用户认证失败:',
        verifyTokenFailed: '验证token失败:',
        resetPasswordFailed: '密码重置失败:',
        title: '邮箱验证',
        verifying: '正在验证邮件链接...',
        verificationFailed: '验证失败',
        verificationSuccess: '验证成功',
        verificationError: '验证失败，请检查链接是否正确或是否已过期',
        missingToken: '缺少验证链接参数',
        resetPassword: '重置密码',
        setNewPassword: '请设置新密码',
        passwordResetSuccess: '密码重置成功',
        passwordResetFailed: '密码重置失败，请稍后重试',
        passwordResetError: '密码重置失败',
        newPassword: '新密码',
        confirmPassword: '确认密码',
        newPasswordRequired: '请输入新密码',
        confirmPasswordRequired: '请确认新密码',
        passwordMinLength: '密码长度至少6位',
        passwordMismatch: '两次输入的密码不一致',
        newPasswordPlaceholder: '请输入新密码',
        confirmPasswordPlaceholder: '请再次输入新密码',
        confirmResetPassword: '确认重置密码',
        missingInfo: '缺少必要信息',
        setPasswordForEcid: '请为 ECID: {ecid} 设置新密码',
        actionDescriptions: {
            clear_security: '清除密保',
            set_security: '设为密保',
            reset_password: '重置密码',
            unbind_ticket: '解绑工单',
        },
        actionCompleted: '{action}操作已完成',
        returnHome: '返回首页',
        viewAccount: '查看账户',
        neteaseAccountWarning:
            '目前暂不支持网易ECID更改密码，更改密码将没有任何作用，但仍支持找回账号等操作',
    },
    wiki: {
        loadDataFailed: '加载数据失败:',
        title: 'Wiki 绑定',
        noEcid: '暂无ECID',
        noBoundWiki: '暂无已绑定的Wiki账号',
        tagBound: '已绑定',
        tagUnbound: '未绑定',
        wikiUserLabel: 'Wiki用户',
        wikiUserIdLabel: 'Wiki用户ID',
        boundAtLabel: '绑定时间',
        getBindingCodeButton: '获取绑定验证码',
        unbind: '解绑',
        unbindConfirm: '确定要解绑该 ECID 与 Wiki 的绑定吗？',
        unbindSuccess: '解绑成功',
        unbindFailed: '解绑失败',
        welcomeDesc1: '这里提供了与Wiki相关的实用工具，包括图片处理和账号绑定功能。',
        alreadyBound: '已绑定WIKI账号',
        bindingStatus: {
            bound: '已绑定WIKI账号',
            notBound: '尚未绑定WIKI账号',
            notBoundDesc: '您可以点击下方工具进行绑定申请',
        },
        tools: {
            wikiBinding: {
                title: 'WIKI绑定申请',
                description: '申请将ECID绑定到WIKI用户账号',
                boundAccount: '已绑定账号: {username}',
            },
            wikiRebinding: {
                title: 'WIKI换绑申请',
                description: '申请更换WIKI用户账号绑定',
            },
        },
        binding: {
            title: 'WIKI绑定工单',
            description: '申请将ECID绑定到WIKI用户账号',
            form: {
                ecidLabel: '选择要绑定的ECID',
                ecidPlaceholder: '请选择ECID',
                ecidExtra: '请选择您要绑定到WIKI的ECID账号',
                wikiUsernameLabel: 'WIKI用户名',
                wikiUsernamePlaceholder: '请输入您的WIKI用户名',
                wikiUsernameExtra: '请输入您在WIKI上的用户名',
                titleLabel: '工单标题',
                titlePlaceholder: '请输入工单标题',
                contentLabel: '备注',
                contentExtra: '选填',
                screenshotLabel: 'WIKI截图',
                screenshotHelp: '请上传WIKI参数设置页面截图',
                screenshotUploadText: '上传截图',
                screenshotLimit: '最多上传5张图片，支持JPG、PNG格式',
                submitButton: '提交申请',
                cancelButton: '返回工单列表',
                selectEcid: '请选择要绑定的ECID',
                enterWikiUsername: '请输入WIKI用户名',
                uploadWikiScreenshot: '请上传WIKI截图',
                wikiUsernameMaxLength: 'WIKI用户名最多50个字符',
                submitTicketSuccess: '工单提交成功',
                submitTicketFailed: '提交工单失败',
                wikiUserPageUrl: 'https://wiki.easecation.net/用户:{username}',
                applyBindContent: '申请将ECID {ecid} 绑定到WIKI用户 {username}',
                wikiUserPageContent: 'WIKI用户页面: {url}',
                remarkContent: '备注: {content}',
                frozenAccount: '(已冻结)',
            },
        },
    },
};

/**
 * 根据错误代码获取多语言错误消息
 * @param errorCode 后端返回的错误代码
 * @param defaultMessage 默认错误消息（如果找不到对应的多语言文本）
 * @returns 多语言错误消息
 */
export const getErrorMessage = (errorCode: number, defaultMessage?: string): string => {
    const staffAliasConfig = languageConfig.staffAlias as any;
    const errorCodeMap = staffAliasConfig?.errorCode;
    if (errorCodeMap && typeof errorCodeMap === 'object' && errorCode in errorCodeMap) {
        const errorKey = errorCodeMap[errorCode];
        if (typeof errorKey === 'string') {
            const path = `staffAlias.message.${errorKey}`;
            const msg = gLang(path);
            return msg === path ? defaultMessage || String(errorCode) : msg;
        }
    }
    return defaultMessage || String(errorCode);
};

export const gLang = (path: string, params?: { [key: string]: string | number }): string => {
    const keys = path.split('.');
    let result: any = languageConfig;

    for (const key of keys) {
        if (result && typeof result === 'object' && key in result) {
            result = result[key];
        } else {
            return path; // Path not found, return original path
        }
    }

    if (typeof result === 'string' && params) {
        for (const [paramKey, paramValue] of Object.entries(params)) {
            result = result.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue));
        }
    }

    return typeof result === 'string' ? result : path;
};
